// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class Addressing private constructor() {
    companion object {
        const val FUNCTIONAL: Byte = 0
        const val PHYSICAL: Byte = 1
        const val FUNCTIONAL_OR_PHYSICAL: Byte = 2
    }
}
