// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Audience : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Audience {
        __init(_i, _bb)
        return this
    }
    fun enabledAudiences(j: Int) : dataformat.AdditionalAudience? = enabledAudiences(dataformat.AdditionalAudience(), j)
    fun enabledAudiences(obj: dataformat.AdditionalAudience, j: Int) : dataformat.AdditionalAudience? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val enabledAudiencesLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    fun disabledAudiences(j: Int) : dataformat.AdditionalAudience? = disabledAudiences(dataformat.AdditionalAudience(), j)
    fun disabledAudiences(obj: dataformat.AdditionalAudience, j: Int) : dataformat.AdditionalAudience? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val disabledAudiencesLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val isSupplier : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isDevelopment : Boolean
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isManufacturing : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isAfterSales : Boolean
        get() {
            val o = __offset(14)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isAfterMarket : Boolean
        get() {
            val o = __offset(16)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsAudience(_bb: ByteBuffer): Audience = getRootAsAudience(_bb, Audience())
        fun getRootAsAudience(_bb: ByteBuffer, obj: Audience): Audience {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createAudience(builder: FlatBufferBuilder, enabledAudiencesOffset: Int, disabledAudiencesOffset: Int, isSupplier: Boolean, isDevelopment: Boolean, isManufacturing: Boolean, isAfterSales: Boolean, isAfterMarket: Boolean) : Int {
            builder.startTable(7)
            addDisabledAudiences(builder, disabledAudiencesOffset)
            addEnabledAudiences(builder, enabledAudiencesOffset)
            addIsAfterMarket(builder, isAfterMarket)
            addIsAfterSales(builder, isAfterSales)
            addIsManufacturing(builder, isManufacturing)
            addIsDevelopment(builder, isDevelopment)
            addIsSupplier(builder, isSupplier)
            return endAudience(builder)
        }
        fun startAudience(builder: FlatBufferBuilder) = builder.startTable(7)
        fun addEnabledAudiences(builder: FlatBufferBuilder, enabledAudiences: Int) = builder.addOffset(0, enabledAudiences, 0)
        fun createEnabledAudiencesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startEnabledAudiencesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDisabledAudiences(builder: FlatBufferBuilder, disabledAudiences: Int) = builder.addOffset(1, disabledAudiences, 0)
        fun createDisabledAudiencesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDisabledAudiencesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addIsSupplier(builder: FlatBufferBuilder, isSupplier: Boolean) = builder.addBoolean(2, isSupplier, false)
        fun addIsDevelopment(builder: FlatBufferBuilder, isDevelopment: Boolean) = builder.addBoolean(3, isDevelopment, false)
        fun addIsManufacturing(builder: FlatBufferBuilder, isManufacturing: Boolean) = builder.addBoolean(4, isManufacturing, false)
        fun addIsAfterSales(builder: FlatBufferBuilder, isAfterSales: Boolean) = builder.addBoolean(5, isAfterSales, false)
        fun addIsAfterMarket(builder: FlatBufferBuilder, isAfterMarket: Boolean) = builder.addBoolean(6, isAfterMarket, false)
        fun endAudience(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
