// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Case : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Case {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val structure : dataformat.DOP? get() = structure(dataformat.DOP())
    fun structure(obj: dataformat.DOP) : dataformat.DOP? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val lowerLimit : dataformat.Limit? get() = lowerLimit(dataformat.Limit())
    fun lowerLimit(obj: dataformat.Limit) : dataformat.Limit? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val upperLimit : dataformat.Limit? get() = upperLimit(dataformat.Limit())
    fun upperLimit(obj: dataformat.Limit) : dataformat.Limit? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsCase(_bb: ByteBuffer): Case = getRootAsCase(_bb, Case())
        fun getRootAsCase(_bb: ByteBuffer, obj: Case): Case {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCase(builder: FlatBufferBuilder, shortNameOffset: Int, longNameOffset: Int, structureOffset: Int, lowerLimitOffset: Int, upperLimitOffset: Int) : Int {
            builder.startTable(5)
            addUpperLimit(builder, upperLimitOffset)
            addLowerLimit(builder, lowerLimitOffset)
            addStructure(builder, structureOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            return endCase(builder)
        }
        fun startCase(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(1, longName, 0)
        fun addStructure(builder: FlatBufferBuilder, structure: Int) = builder.addOffset(2, structure, 0)
        fun addLowerLimit(builder: FlatBufferBuilder, lowerLimit: Int) = builder.addOffset(3, lowerLimit, 0)
        fun addUpperLimit(builder: FlatBufferBuilder, upperLimit: Int) = builder.addOffset(4, upperLimit, 0)
        fun endCase(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
