// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class CodedConst : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CodedConst {
        __init(_i, _bb)
        return this
    }
    val codedValue : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val codedValueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun codedValueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val diagCodedType : dataformat.DiagCodedType? get() = diagCodedType(dataformat.DiagCodedType())
    fun diagCodedType(obj: dataformat.DiagCodedType) : dataformat.DiagCodedType? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsCodedConst(_bb: ByteBuffer): CodedConst = getRootAsCodedConst(_bb, CodedConst())
        fun getRootAsCodedConst(_bb: ByteBuffer, obj: CodedConst): CodedConst {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCodedConst(builder: FlatBufferBuilder, codedValueOffset: Int, diagCodedTypeOffset: Int) : Int {
            builder.startTable(2)
            addDiagCodedType(builder, diagCodedTypeOffset)
            addCodedValue(builder, codedValueOffset)
            return endCodedConst(builder)
        }
        fun startCodedConst(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addCodedValue(builder: FlatBufferBuilder, codedValue: Int) = builder.addOffset(0, codedValue, 0)
        fun addDiagCodedType(builder: FlatBufferBuilder, diagCodedType: Int) = builder.addOffset(1, diagCodedType, 0)
        fun endCodedConst(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
