// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ComplexComParam : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ComplexComParam {
        __init(_i, _bb)
        return this
    }
    fun comParams(j: Int) : dataformat.ComParam? = comParams(dataformat.ComParam(), j)
    fun comParams(obj: dataformat.ComParam, j: Int) : dataformat.ComParam? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val comParamsLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    fun complexPhysicalDefaultValues(j: Int) : dataformat.ComplexValue? = complexPhysicalDefaultValues(dataformat.ComplexValue(), j)
    fun complexPhysicalDefaultValues(obj: dataformat.ComplexValue, j: Int) : dataformat.ComplexValue? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val complexPhysicalDefaultValuesLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val allowMultipleValues : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsComplexComParam(_bb: ByteBuffer): ComplexComParam = getRootAsComplexComParam(_bb, ComplexComParam())
        fun getRootAsComplexComParam(_bb: ByteBuffer, obj: ComplexComParam): ComplexComParam {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createComplexComParam(builder: FlatBufferBuilder, comParamsOffset: Int, complexPhysicalDefaultValuesOffset: Int, allowMultipleValues: Boolean) : Int {
            builder.startTable(3)
            addComplexPhysicalDefaultValues(builder, complexPhysicalDefaultValuesOffset)
            addComParams(builder, comParamsOffset)
            addAllowMultipleValues(builder, allowMultipleValues)
            return endComplexComParam(builder)
        }
        fun startComplexComParam(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addComParams(builder: FlatBufferBuilder, comParams: Int) = builder.addOffset(0, comParams, 0)
        fun createComParamsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startComParamsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addComplexPhysicalDefaultValues(builder: FlatBufferBuilder, complexPhysicalDefaultValues: Int) = builder.addOffset(1, complexPhysicalDefaultValues, 0)
        fun createComplexPhysicalDefaultValuesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startComplexPhysicalDefaultValuesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addAllowMultipleValues(builder: FlatBufferBuilder, allowMultipleValues: Boolean) = builder.addBoolean(2, allowMultipleValues, false)
        fun endComplexComParam(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
