// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class ComParamType private constructor() {
    companion object {
        const val REGULAR: Byte = 0
        const val COMPLEX: Byte = 1
    }
}
