// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ComParamRef : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ComParamRef {
        __init(_i, _bb)
        return this
    }
    val simpleValue : dataformat.SimpleValue? get() = simpleValue(dataformat.SimpleValue())
    fun simpleValue(obj: dataformat.SimpleValue) : dataformat.SimpleValue? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val complexValue : dataformat.ComplexValue? get() = complexValue(dataformat.ComplexValue())
    fun complexValue(obj: dataformat.ComplexValue) : dataformat.ComplexValue? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val comParam : dataformat.ComParam? get() = comParam(dataformat.ComParam())
    fun comParam(obj: dataformat.ComParam) : dataformat.ComParam? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val protocol : dataformat.Protocol? get() = protocol(dataformat.Protocol())
    fun protocol(obj: dataformat.Protocol) : dataformat.Protocol? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val protStack : dataformat.ProtStack? get() = protStack(dataformat.ProtStack())
    fun protStack(obj: dataformat.ProtStack) : dataformat.ProtStack? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsComParamRef(_bb: ByteBuffer): ComParamRef = getRootAsComParamRef(_bb, ComParamRef())
        fun getRootAsComParamRef(_bb: ByteBuffer, obj: ComParamRef): ComParamRef {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createComParamRef(builder: FlatBufferBuilder, simpleValueOffset: Int, complexValueOffset: Int, comParamOffset: Int, protocolOffset: Int, protStackOffset: Int) : Int {
            builder.startTable(5)
            addProtStack(builder, protStackOffset)
            addProtocol(builder, protocolOffset)
            addComParam(builder, comParamOffset)
            addComplexValue(builder, complexValueOffset)
            addSimpleValue(builder, simpleValueOffset)
            return endComParamRef(builder)
        }
        fun startComParamRef(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addSimpleValue(builder: FlatBufferBuilder, simpleValue: Int) = builder.addOffset(0, simpleValue, 0)
        fun addComplexValue(builder: FlatBufferBuilder, complexValue: Int) = builder.addOffset(1, complexValue, 0)
        fun addComParam(builder: FlatBufferBuilder, comParam: Int) = builder.addOffset(2, comParam, 0)
        fun addProtocol(builder: FlatBufferBuilder, protocol: Int) = builder.addOffset(3, protocol, 0)
        fun addProtStack(builder: FlatBufferBuilder, protStack: Int) = builder.addOffset(4, protStack, 0)
        fun endComParamRef(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
