// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class ComParamUsage private constructor() {
    companion object {
        const val ECU_SOFTWARE: Byte = 0
        const val ECU_COMM: Byte = 1
        const val APPLICATION: Byte = 2
        const val TESTER: Byte = 3
    }
}
