// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class CompuRationalCoEffs : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CompuRationalCoEffs {
        __init(_i, _bb)
        return this
    }
    fun numerator(j: Int) : Double {
        val o = __offset(4)
        return if (o != 0) {
            bb.getDouble(__vector(o) + j * 8)
        } else {
            0.0
        }
    }
    val numeratorLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val numeratorAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 8)
    fun numeratorInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 8)
    fun denominator(j: Int) : Double {
        val o = __offset(6)
        return if (o != 0) {
            bb.getDouble(__vector(o) + j * 8)
        } else {
            0.0
        }
    }
    val denominatorLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val denominatorAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 8)
    fun denominatorInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 8)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsCompuRationalCoEffs(_bb: ByteBuffer): CompuRationalCoEffs = getRootAsCompuRationalCoEffs(_bb, CompuRationalCoEffs())
        fun getRootAsCompuRationalCoEffs(_bb: ByteBuffer, obj: CompuRationalCoEffs): CompuRationalCoEffs {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCompuRationalCoEffs(builder: FlatBufferBuilder, numeratorOffset: Int, denominatorOffset: Int) : Int {
            builder.startTable(2)
            addDenominator(builder, denominatorOffset)
            addNumerator(builder, numeratorOffset)
            return endCompuRationalCoEffs(builder)
        }
        fun startCompuRationalCoEffs(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addNumerator(builder: FlatBufferBuilder, numerator: Int) = builder.addOffset(0, numerator, 0)
        fun createNumeratorVector(builder: FlatBufferBuilder, data: DoubleArray) : Int {
            builder.startVector(8, data.size, 8)
            for (i in data.size - 1 downTo 0) {
                builder.addDouble(data[i])
            }
            return builder.endVector()
        }
        fun startNumeratorVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(8, numElems, 8)
        fun addDenominator(builder: FlatBufferBuilder, denominator: Int) = builder.addOffset(1, denominator, 0)
        fun createDenominatorVector(builder: FlatBufferBuilder, data: DoubleArray) : Int {
            builder.startVector(8, data.size, 8)
            for (i in data.size - 1 downTo 0) {
                builder.addDouble(data[i])
            }
            return builder.endVector()
        }
        fun startDenominatorVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(8, numElems, 8)
        fun endCompuRationalCoEffs(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
