// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ComParamSpec : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ComParamSpec {
        __init(_i, _bb)
        return this
    }
    fun protStacks(j: Int) : dataformat.ProtStack? = protStacks(dataformat.ProtStack(), j)
    fun protStacks(obj: dataformat.ProtStack, j: Int) : dataformat.ProtStack? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val protStacksLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsComParamSpec(_bb: ByteBuffer): ComParamSpec = getRootAsComParamSpec(_bb, ComParamSpec())
        fun getRootAsComParamSpec(_bb: ByteBuffer, obj: ComParamSpec): ComParamSpec {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createComParamSpec(builder: FlatBufferBuilder, protStacksOffset: Int) : Int {
            builder.startTable(1)
            addProtStacks(builder, protStacksOffset)
            return endComParamSpec(builder)
        }
        fun startComParamSpec(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addProtStacks(builder: FlatBufferBuilder, protStacks: Int) = builder.addOffset(0, protStacks, 0)
        fun createProtStacksVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startProtStacksVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endComParamSpec(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
