// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class CompuMethod : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CompuMethod {
        __init(_i, _bb)
        return this
    }
    val category : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val internalToPhys : dataformat.CompuInternalToPhys? get() = internalToPhys(dataformat.CompuInternalToPhys())
    fun internalToPhys(obj: dataformat.CompuInternalToPhys) : dataformat.CompuInternalToPhys? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val physToInternal : dataformat.CompuPhysToInternal? get() = physToInternal(dataformat.CompuPhysToInternal())
    fun physToInternal(obj: dataformat.CompuPhysToInternal) : dataformat.CompuPhysToInternal? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsCompuMethod(_bb: ByteBuffer): CompuMethod = getRootAsCompuMethod(_bb, CompuMethod())
        fun getRootAsCompuMethod(_bb: ByteBuffer, obj: CompuMethod): CompuMethod {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCompuMethod(builder: FlatBufferBuilder, category: Byte, internalToPhysOffset: Int, physToInternalOffset: Int) : Int {
            builder.startTable(3)
            addPhysToInternal(builder, physToInternalOffset)
            addInternalToPhys(builder, internalToPhysOffset)
            addCategory(builder, category)
            return endCompuMethod(builder)
        }
        fun startCompuMethod(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addCategory(builder: FlatBufferBuilder, category: Byte) = builder.addByte(0, category, 0)
        fun addInternalToPhys(builder: FlatBufferBuilder, internalToPhys: Int) = builder.addOffset(1, internalToPhys, 0)
        fun addPhysToInternal(builder: FlatBufferBuilder, physToInternal: Int) = builder.addOffset(2, physToInternal, 0)
        fun endCompuMethod(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
