// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class ComParamStandardisationLevel private constructor() {
    companion object {
        const val STANDARD: Byte = 0
        const val OEM_SPECIFIC: Byte = 1
        const val OPTIONAL: Byte = 2
        const val OEM_OPTIONAL: Byte = 3
    }
}
