// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class CompuCategory private constructor() {
    companion object {
        const val IDENTICAL: Byte = 0
        const val LINEAR: Byte = 1
        const val SCALE_LINEAR: Byte = 2
        const val TEXT_TABLE: Byte = 3
        const val COMPU_CODE: Byte = 4
        const val TAB_INTP: Byte = 5
        const val RAT_FUNC: Byte = 6
        const val SCALE_RAT_FUNC: Byte = 7
    }
}
