// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ComParam : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ComParam {
        __init(_i, _bb)
        return this
    }
    val comParamType : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val shortName : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val paramClass : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val paramClassAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun paramClassInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val cpType : Byte
        get() {
            val o = __offset(12)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val displayLevel : UInt?
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else null
        }
    val cpUsage : Byte
        get() {
            val o = __offset(16)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val specificDataType : UByte
        get() {
            val o = __offset(18)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun specificData(obj: Table) : Table? {
        val o = __offset(20); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsComParam(_bb: ByteBuffer): ComParam = getRootAsComParam(_bb, ComParam())
        fun getRootAsComParam(_bb: ByteBuffer, obj: ComParam): ComParam {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createComParam(builder: FlatBufferBuilder, comParamType: Byte, shortNameOffset: Int, longNameOffset: Int, paramClassOffset: Int, cpType: Byte, displayLevel: UInt?, cpUsage: Byte, specificDataType: UByte, specificDataOffset: Int) : Int {
            builder.startTable(9)
            addSpecificData(builder, specificDataOffset)
            displayLevel?.run { addDisplayLevel(builder, displayLevel) }
            addParamClass(builder, paramClassOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            addSpecificDataType(builder, specificDataType)
            addCpUsage(builder, cpUsage)
            addCpType(builder, cpType)
            addComParamType(builder, comParamType)
            return endComParam(builder)
        }
        fun startComParam(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addComParamType(builder: FlatBufferBuilder, comParamType: Byte) = builder.addByte(0, comParamType, 0)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(1, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(2, longName, 0)
        fun addParamClass(builder: FlatBufferBuilder, paramClass: Int) = builder.addOffset(3, paramClass, 0)
        fun addCpType(builder: FlatBufferBuilder, cpType: Byte) = builder.addByte(4, cpType, 0)
        fun addDisplayLevel(builder: FlatBufferBuilder, displayLevel: UInt) = builder.addInt(5, displayLevel.toInt(), 0)
        fun addCpUsage(builder: FlatBufferBuilder, cpUsage: Byte) = builder.addByte(6, cpUsage, 0)
        fun addSpecificDataType(builder: FlatBufferBuilder, specificDataType: UByte) = builder.addByte(7, specificDataType.toByte(), 0)
        fun addSpecificData(builder: FlatBufferBuilder, specificData: Int) = builder.addOffset(8, specificData, 0)
        fun endComParam(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
