// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class CompuPhysToInternal : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CompuPhysToInternal {
        __init(_i, _bb)
        return this
    }
    val progCode : dataformat.ProgCode? get() = progCode(dataformat.ProgCode())
    fun progCode(obj: dataformat.ProgCode) : dataformat.ProgCode? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun compuScales(j: Int) : dataformat.CompuScale? = compuScales(dataformat.CompuScale(), j)
    fun compuScales(obj: dataformat.CompuScale, j: Int) : dataformat.CompuScale? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val compuScalesLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val compuDefaultValue : dataformat.CompuDefaultValue? get() = compuDefaultValue(dataformat.CompuDefaultValue())
    fun compuDefaultValue(obj: dataformat.CompuDefaultValue) : dataformat.CompuDefaultValue? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsCompuPhysToInternal(_bb: ByteBuffer): CompuPhysToInternal = getRootAsCompuPhysToInternal(_bb, CompuPhysToInternal())
        fun getRootAsCompuPhysToInternal(_bb: ByteBuffer, obj: CompuPhysToInternal): CompuPhysToInternal {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCompuPhysToInternal(builder: FlatBufferBuilder, progCodeOffset: Int, compuScalesOffset: Int, compuDefaultValueOffset: Int) : Int {
            builder.startTable(3)
            addCompuDefaultValue(builder, compuDefaultValueOffset)
            addCompuScales(builder, compuScalesOffset)
            addProgCode(builder, progCodeOffset)
            return endCompuPhysToInternal(builder)
        }
        fun startCompuPhysToInternal(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addProgCode(builder: FlatBufferBuilder, progCode: Int) = builder.addOffset(0, progCode, 0)
        fun addCompuScales(builder: FlatBufferBuilder, compuScales: Int) = builder.addOffset(1, compuScales, 0)
        fun createCompuScalesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startCompuScalesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addCompuDefaultValue(builder: FlatBufferBuilder, compuDefaultValue: Int) = builder.addOffset(2, compuDefaultValue, 0)
        fun endCompuPhysToInternal(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
