// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class CompuScale : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CompuScale {
        __init(_i, _bb)
        return this
    }
    val shortLabel : dataformat.Text? get() = shortLabel(dataformat.Text())
    fun shortLabel(obj: dataformat.Text) : dataformat.Text? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val lowerLimit : dataformat.Limit? get() = lowerLimit(dataformat.Limit())
    fun lowerLimit(obj: dataformat.Limit) : dataformat.Limit? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val upperLimit : dataformat.Limit? get() = upperLimit(dataformat.Limit())
    fun upperLimit(obj: dataformat.Limit) : dataformat.Limit? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val inverseValues : dataformat.CompuValues? get() = inverseValues(dataformat.CompuValues())
    fun inverseValues(obj: dataformat.CompuValues) : dataformat.CompuValues? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val consts : dataformat.CompuValues? get() = consts(dataformat.CompuValues())
    fun consts(obj: dataformat.CompuValues) : dataformat.CompuValues? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val rationalCoEffs : dataformat.CompuRationalCoEffs? get() = rationalCoEffs(dataformat.CompuRationalCoEffs())
    fun rationalCoEffs(obj: dataformat.CompuRationalCoEffs) : dataformat.CompuRationalCoEffs? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsCompuScale(_bb: ByteBuffer): CompuScale = getRootAsCompuScale(_bb, CompuScale())
        fun getRootAsCompuScale(_bb: ByteBuffer, obj: CompuScale): CompuScale {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCompuScale(builder: FlatBufferBuilder, shortLabelOffset: Int, lowerLimitOffset: Int, upperLimitOffset: Int, inverseValuesOffset: Int, constsOffset: Int, rationalCoEffsOffset: Int) : Int {
            builder.startTable(6)
            addRationalCoEffs(builder, rationalCoEffsOffset)
            addConsts(builder, constsOffset)
            addInverseValues(builder, inverseValuesOffset)
            addUpperLimit(builder, upperLimitOffset)
            addLowerLimit(builder, lowerLimitOffset)
            addShortLabel(builder, shortLabelOffset)
            return endCompuScale(builder)
        }
        fun startCompuScale(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addShortLabel(builder: FlatBufferBuilder, shortLabel: Int) = builder.addOffset(0, shortLabel, 0)
        fun addLowerLimit(builder: FlatBufferBuilder, lowerLimit: Int) = builder.addOffset(1, lowerLimit, 0)
        fun addUpperLimit(builder: FlatBufferBuilder, upperLimit: Int) = builder.addOffset(2, upperLimit, 0)
        fun addInverseValues(builder: FlatBufferBuilder, inverseValues: Int) = builder.addOffset(3, inverseValues, 0)
        fun addConsts(builder: FlatBufferBuilder, consts: Int) = builder.addOffset(4, consts, 0)
        fun addRationalCoEffs(builder: FlatBufferBuilder, rationalCoEffs: Int) = builder.addOffset(5, rationalCoEffs, 0)
        fun endCompuScale(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
