// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ComParamSubSet : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ComParamSubSet {
        __init(_i, _bb)
        return this
    }
    fun comParams(j: Int) : dataformat.ComParam? = comParams(dataformat.ComParam(), j)
    fun comParams(obj: dataformat.ComParam, j: Int) : dataformat.ComParam? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val comParamsLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    fun complexComParams(j: Int) : dataformat.ComParam? = complexComParams(dataformat.ComParam(), j)
    fun complexComParams(obj: dataformat.ComParam, j: Int) : dataformat.ComParam? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val complexComParamsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    fun dataObjectProps(j: Int) : dataformat.DOP? = dataObjectProps(dataformat.DOP(), j)
    fun dataObjectProps(obj: dataformat.DOP, j: Int) : dataformat.DOP? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val dataObjectPropsLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val unitSpec : dataformat.UnitSpec? get() = unitSpec(dataformat.UnitSpec())
    fun unitSpec(obj: dataformat.UnitSpec) : dataformat.UnitSpec? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsComParamSubSet(_bb: ByteBuffer): ComParamSubSet = getRootAsComParamSubSet(_bb, ComParamSubSet())
        fun getRootAsComParamSubSet(_bb: ByteBuffer, obj: ComParamSubSet): ComParamSubSet {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createComParamSubSet(builder: FlatBufferBuilder, comParamsOffset: Int, complexComParamsOffset: Int, dataObjectPropsOffset: Int, unitSpecOffset: Int) : Int {
            builder.startTable(4)
            addUnitSpec(builder, unitSpecOffset)
            addDataObjectProps(builder, dataObjectPropsOffset)
            addComplexComParams(builder, complexComParamsOffset)
            addComParams(builder, comParamsOffset)
            return endComParamSubSet(builder)
        }
        fun startComParamSubSet(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addComParams(builder: FlatBufferBuilder, comParams: Int) = builder.addOffset(0, comParams, 0)
        fun createComParamsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startComParamsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addComplexComParams(builder: FlatBufferBuilder, complexComParams: Int) = builder.addOffset(1, complexComParams, 0)
        fun createComplexComParamsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startComplexComParamsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDataObjectProps(builder: FlatBufferBuilder, dataObjectProps: Int) = builder.addOffset(2, dataObjectProps, 0)
        fun createDataObjectPropsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDataObjectPropsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addUnitSpec(builder: FlatBufferBuilder, unitSpec: Int) = builder.addOffset(3, unitSpec, 0)
        fun endComParamSubSet(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
