// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class CompuDefaultValue : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CompuDefaultValue {
        __init(_i, _bb)
        return this
    }
    val values : dataformat.CompuValues? get() = values(dataformat.CompuValues())
    fun values(obj: dataformat.CompuValues) : dataformat.CompuValues? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val inverseValues : dataformat.CompuValues? get() = inverseValues(dataformat.CompuValues())
    fun inverseValues(obj: dataformat.CompuValues) : dataformat.CompuValues? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsCompuDefaultValue(_bb: ByteBuffer): CompuDefaultValue = getRootAsCompuDefaultValue(_bb, CompuDefaultValue())
        fun getRootAsCompuDefaultValue(_bb: ByteBuffer, obj: CompuDefaultValue): CompuDefaultValue {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCompuDefaultValue(builder: FlatBufferBuilder, valuesOffset: Int, inverseValuesOffset: Int) : Int {
            builder.startTable(2)
            addInverseValues(builder, inverseValuesOffset)
            addValues(builder, valuesOffset)
            return endCompuDefaultValue(builder)
        }
        fun startCompuDefaultValue(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addValues(builder: FlatBufferBuilder, values: Int) = builder.addOffset(0, values, 0)
        fun addInverseValues(builder: FlatBufferBuilder, inverseValues: Int) = builder.addOffset(1, inverseValues, 0)
        fun endCompuDefaultValue(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
