// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class ComParamSpecificData private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val RegularComParam: UByte = 1u
        const val ComplexComParam: UByte = 2u
    }
}
