// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class CompuValues : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CompuValues {
        __init(_i, _bb)
        return this
    }
    val v : Double?
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getDouble(o + bb_pos) else null
        }
    val vt : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val vtAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun vtInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val vtTi : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val vtTiAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun vtTiInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsCompuValues(_bb: ByteBuffer): CompuValues = getRootAsCompuValues(_bb, CompuValues())
        fun getRootAsCompuValues(_bb: ByteBuffer, obj: CompuValues): CompuValues {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCompuValues(builder: FlatBufferBuilder, v: Double?, vtOffset: Int, vtTiOffset: Int) : Int {
            builder.startTable(3)
            v?.run { addV(builder, v) }
            addVtTi(builder, vtTiOffset)
            addVt(builder, vtOffset)
            return endCompuValues(builder)
        }
        fun startCompuValues(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addV(builder: FlatBufferBuilder, v: Double) = builder.addDouble(0, v, 0.0)
        fun addVt(builder: FlatBufferBuilder, vt: Int) = builder.addOffset(1, vt, 0)
        fun addVtTi(builder: FlatBufferBuilder, vtTi: Int) = builder.addOffset(2, vtTi, 0)
        fun endCompuValues(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
