// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class DataType private constructor() {
    companion object {
        const val A_INT_32: Byte = 0
        const val A_UINT_32: Byte = 1
        const val A_FLOAT_32: Byte = 2
        const val A_ASCIISTRING: Byte = 3
        const val A_UTF_8_STRING: Byte = 4
        const val A_UNICODE_2_STRING: Byte = 5
        const val A_BYTEFIELD: Byte = 6
        const val A_FLOAT_64: Byte = 7
    }
}
