// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DefaultCase : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DefaultCase {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val structure : dataformat.DOP? get() = structure(dataformat.DOP())
    fun structure(obj: dataformat.DOP) : dataformat.DOP? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsDefaultCase(_bb: ByteBuffer): DefaultCase = getRootAsDefaultCase(_bb, DefaultCase())
        fun getRootAsDefaultCase(_bb: ByteBuffer, obj: DefaultCase): DefaultCase {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDefaultCase(builder: FlatBufferBuilder, shortNameOffset: Int, longNameOffset: Int, structureOffset: Int) : Int {
            builder.startTable(3)
            addStructure(builder, structureOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            return endDefaultCase(builder)
        }
        fun startDefaultCase(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(1, longName, 0)
        fun addStructure(builder: FlatBufferBuilder, structure: Int) = builder.addOffset(2, structure, 0)
        fun endDefaultCase(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
