// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DetermineNumberOfItems : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DetermineNumberOfItems {
        __init(_i, _bb)
        return this
    }
    val bytePosition : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val bitPosition : UInt
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val dop : dataformat.DOP? get() = dop(dataformat.DOP())
    fun dop(obj: dataformat.DOP) : dataformat.DOP? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsDetermineNumberOfItems(_bb: ByteBuffer): DetermineNumberOfItems = getRootAsDetermineNumberOfItems(_bb, DetermineNumberOfItems())
        fun getRootAsDetermineNumberOfItems(_bb: ByteBuffer, obj: DetermineNumberOfItems): DetermineNumberOfItems {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDetermineNumberOfItems(builder: FlatBufferBuilder, bytePosition: UInt, bitPosition: UInt, dopOffset: Int) : Int {
            builder.startTable(3)
            addDop(builder, dopOffset)
            addBitPosition(builder, bitPosition)
            addBytePosition(builder, bytePosition)
            return endDetermineNumberOfItems(builder)
        }
        fun startDetermineNumberOfItems(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addBytePosition(builder: FlatBufferBuilder, bytePosition: UInt) = builder.addInt(0, bytePosition.toInt(), 0)
        fun addBitPosition(builder: FlatBufferBuilder, bitPosition: UInt) = builder.addInt(1, bitPosition.toInt(), 0)
        fun addDop(builder: FlatBufferBuilder, dop: Int) = builder.addOffset(2, dop, 0)
        fun endDetermineNumberOfItems(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
