// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class DiagServiceOrJob private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val DiagService: UByte = 1u
        const val SingleEcuJob: UByte = 2u
    }
}
