// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DiagCodedType : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DiagCodedType {
        __init(_i, _bb)
        return this
    }
    val type : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val baseTypeEncoding : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val baseTypeEncodingAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun baseTypeEncodingInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val baseDataType : Byte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val isHighLowByteOrder : Boolean
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else true
        }
    val specificDataType : UByte
        get() {
            val o = __offset(12)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun specificData(obj: Table) : Table? {
        val o = __offset(14); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsDiagCodedType(_bb: ByteBuffer): DiagCodedType = getRootAsDiagCodedType(_bb, DiagCodedType())
        fun getRootAsDiagCodedType(_bb: ByteBuffer, obj: DiagCodedType): DiagCodedType {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDiagCodedType(builder: FlatBufferBuilder, type: Byte, baseTypeEncodingOffset: Int, baseDataType: Byte, isHighLowByteOrder: Boolean, specificDataType: UByte, specificDataOffset: Int) : Int {
            builder.startTable(6)
            addSpecificData(builder, specificDataOffset)
            addBaseTypeEncoding(builder, baseTypeEncodingOffset)
            addSpecificDataType(builder, specificDataType)
            addIsHighLowByteOrder(builder, isHighLowByteOrder)
            addBaseDataType(builder, baseDataType)
            addType(builder, type)
            return endDiagCodedType(builder)
        }
        fun startDiagCodedType(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addType(builder: FlatBufferBuilder, type: Byte) = builder.addByte(0, type, 0)
        fun addBaseTypeEncoding(builder: FlatBufferBuilder, baseTypeEncoding: Int) = builder.addOffset(1, baseTypeEncoding, 0)
        fun addBaseDataType(builder: FlatBufferBuilder, baseDataType: Byte) = builder.addByte(2, baseDataType, 0)
        fun addIsHighLowByteOrder(builder: FlatBufferBuilder, isHighLowByteOrder: Boolean) = builder.addBoolean(3, isHighLowByteOrder, true)
        fun addSpecificDataType(builder: FlatBufferBuilder, specificDataType: UByte) = builder.addByte(4, specificDataType.toByte(), 0)
        fun addSpecificData(builder: FlatBufferBuilder, specificData: Int) = builder.addOffset(5, specificData, 0)
        fun endDiagCodedType(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
