// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class DiagClassType private constructor() {
    companion object {
        const val START_COMM: Byte = 0
        const val STOP_COMM: Byte = 1
        const val VARIANT_IDENTIFICATION: Byte = 2
        const val READ_DYN_DEF_MESSAGE: Byte = 3
        const val DYN_DEF_MESSAGE: Byte = 4
        const val CLEAR_DYN_DEF_MESSAGE: Byte = 5
    }
}
