// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DiagComm : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DiagComm {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val semantic : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val semanticAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun semanticInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    fun functClass(j: Int) : dataformat.FunctClass? = functClass(dataformat.FunctClass(), j)
    fun functClass(obj: dataformat.FunctClass, j: Int) : dataformat.FunctClass? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val functClassLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    val sdgs : dataformat.SDGS? get() = sdgs(dataformat.SDGS())
    fun sdgs(obj: dataformat.SDGS) : dataformat.SDGS? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val diagClassType : Byte
        get() {
            val o = __offset(14)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    fun preConditionStateRefs(j: Int) : dataformat.PreConditionStateRef? = preConditionStateRefs(dataformat.PreConditionStateRef(), j)
    fun preConditionStateRefs(obj: dataformat.PreConditionStateRef, j: Int) : dataformat.PreConditionStateRef? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val preConditionStateRefsLength : Int
        get() {
            val o = __offset(16); return if (o != 0) __vector_len(o) else 0
        }
    fun stateTransitionRefs(j: Int) : dataformat.StateTransitionRef? = stateTransitionRefs(dataformat.StateTransitionRef(), j)
    fun stateTransitionRefs(obj: dataformat.StateTransitionRef, j: Int) : dataformat.StateTransitionRef? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val stateTransitionRefsLength : Int
        get() {
            val o = __offset(18); return if (o != 0) __vector_len(o) else 0
        }
    fun protocols(j: Int) : dataformat.Protocol? = protocols(dataformat.Protocol(), j)
    fun protocols(obj: dataformat.Protocol, j: Int) : dataformat.Protocol? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val protocolsLength : Int
        get() {
            val o = __offset(20); return if (o != 0) __vector_len(o) else 0
        }
    val audience : dataformat.Audience? get() = audience(dataformat.Audience())
    fun audience(obj: dataformat.Audience) : dataformat.Audience? {
        val o = __offset(22)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val isMandatory : Boolean
        get() {
            val o = __offset(24)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isExecutable : Boolean
        get() {
            val o = __offset(26)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else true
        }
    val isFinal : Boolean
        get() {
            val o = __offset(28)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsDiagComm(_bb: ByteBuffer): DiagComm = getRootAsDiagComm(_bb, DiagComm())
        fun getRootAsDiagComm(_bb: ByteBuffer, obj: DiagComm): DiagComm {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDiagComm(builder: FlatBufferBuilder, shortNameOffset: Int, longNameOffset: Int, semanticOffset: Int, functClassOffset: Int, sdgsOffset: Int, diagClassType: Byte, preConditionStateRefsOffset: Int, stateTransitionRefsOffset: Int, protocolsOffset: Int, audienceOffset: Int, isMandatory: Boolean, isExecutable: Boolean, isFinal: Boolean) : Int {
            builder.startTable(13)
            addAudience(builder, audienceOffset)
            addProtocols(builder, protocolsOffset)
            addStateTransitionRefs(builder, stateTransitionRefsOffset)
            addPreConditionStateRefs(builder, preConditionStateRefsOffset)
            addSdgs(builder, sdgsOffset)
            addFunctClass(builder, functClassOffset)
            addSemantic(builder, semanticOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            addIsFinal(builder, isFinal)
            addIsExecutable(builder, isExecutable)
            addIsMandatory(builder, isMandatory)
            addDiagClassType(builder, diagClassType)
            return endDiagComm(builder)
        }
        fun startDiagComm(builder: FlatBufferBuilder) = builder.startTable(13)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(1, longName, 0)
        fun addSemantic(builder: FlatBufferBuilder, semantic: Int) = builder.addOffset(2, semantic, 0)
        fun addFunctClass(builder: FlatBufferBuilder, functClass: Int) = builder.addOffset(3, functClass, 0)
        fun createFunctClassVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startFunctClassVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(4, sdgs, 0)
        fun addDiagClassType(builder: FlatBufferBuilder, diagClassType: Byte) = builder.addByte(5, diagClassType, 0)
        fun addPreConditionStateRefs(builder: FlatBufferBuilder, preConditionStateRefs: Int) = builder.addOffset(6, preConditionStateRefs, 0)
        fun createPreConditionStateRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startPreConditionStateRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addStateTransitionRefs(builder: FlatBufferBuilder, stateTransitionRefs: Int) = builder.addOffset(7, stateTransitionRefs, 0)
        fun createStateTransitionRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStateTransitionRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addProtocols(builder: FlatBufferBuilder, protocols: Int) = builder.addOffset(8, protocols, 0)
        fun createProtocolsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startProtocolsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addAudience(builder: FlatBufferBuilder, audience: Int) = builder.addOffset(9, audience, 0)
        fun addIsMandatory(builder: FlatBufferBuilder, isMandatory: Boolean) = builder.addBoolean(10, isMandatory, false)
        fun addIsExecutable(builder: FlatBufferBuilder, isExecutable: Boolean) = builder.addBoolean(11, isExecutable, true)
        fun addIsFinal(builder: FlatBufferBuilder, isFinal: Boolean) = builder.addBoolean(12, isFinal, false)
        fun endDiagComm(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
