// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DiagService : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DiagService {
        __init(_i, _bb)
        return this
    }
    val diagComm : dataformat.DiagComm? get() = diagComm(dataformat.DiagComm())
    fun diagComm(obj: dataformat.DiagComm) : dataformat.DiagComm? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val request : dataformat.Request? get() = request(dataformat.Request())
    fun request(obj: dataformat.Request) : dataformat.Request? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun posResponses(j: Int) : dataformat.Response? = posResponses(dataformat.Response(), j)
    fun posResponses(obj: dataformat.Response, j: Int) : dataformat.Response? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val posResponsesLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    fun negResponses(j: Int) : dataformat.Response? = negResponses(dataformat.Response(), j)
    fun negResponses(obj: dataformat.Response, j: Int) : dataformat.Response? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val negResponsesLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    val isCyclic : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isMultiple : Boolean
        get() {
            val o = __offset(14)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val addressing : Byte
        get() {
            val o = __offset(16)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val transmissionMode : Byte
        get() {
            val o = __offset(18)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    fun comParamRefs(j: Int) : dataformat.ComParamRef? = comParamRefs(dataformat.ComParamRef(), j)
    fun comParamRefs(obj: dataformat.ComParamRef, j: Int) : dataformat.ComParamRef? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val comParamRefsLength : Int
        get() {
            val o = __offset(20); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsDiagService(_bb: ByteBuffer): DiagService = getRootAsDiagService(_bb, DiagService())
        fun getRootAsDiagService(_bb: ByteBuffer, obj: DiagService): DiagService {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDiagService(builder: FlatBufferBuilder, diagCommOffset: Int, requestOffset: Int, posResponsesOffset: Int, negResponsesOffset: Int, isCyclic: Boolean, isMultiple: Boolean, addressing: Byte, transmissionMode: Byte, comParamRefsOffset: Int) : Int {
            builder.startTable(9)
            addComParamRefs(builder, comParamRefsOffset)
            addNegResponses(builder, negResponsesOffset)
            addPosResponses(builder, posResponsesOffset)
            addRequest(builder, requestOffset)
            addDiagComm(builder, diagCommOffset)
            addTransmissionMode(builder, transmissionMode)
            addAddressing(builder, addressing)
            addIsMultiple(builder, isMultiple)
            addIsCyclic(builder, isCyclic)
            return endDiagService(builder)
        }
        fun startDiagService(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addDiagComm(builder: FlatBufferBuilder, diagComm: Int) = builder.addOffset(0, diagComm, 0)
        fun addRequest(builder: FlatBufferBuilder, request: Int) = builder.addOffset(1, request, 0)
        fun addPosResponses(builder: FlatBufferBuilder, posResponses: Int) = builder.addOffset(2, posResponses, 0)
        fun createPosResponsesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startPosResponsesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addNegResponses(builder: FlatBufferBuilder, negResponses: Int) = builder.addOffset(3, negResponses, 0)
        fun createNegResponsesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startNegResponsesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addIsCyclic(builder: FlatBufferBuilder, isCyclic: Boolean) = builder.addBoolean(4, isCyclic, false)
        fun addIsMultiple(builder: FlatBufferBuilder, isMultiple: Boolean) = builder.addBoolean(5, isMultiple, false)
        fun addAddressing(builder: FlatBufferBuilder, addressing: Byte) = builder.addByte(6, addressing, 0)
        fun addTransmissionMode(builder: FlatBufferBuilder, transmissionMode: Byte) = builder.addByte(7, transmissionMode, 0)
        fun addComParamRefs(builder: FlatBufferBuilder, comParamRefs: Int) = builder.addOffset(8, comParamRefs, 0)
        fun createComParamRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startComParamRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endDiagService(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
