// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class DiagCodedTypeName private constructor() {
    companion object {
        const val LEADING_LENGTH_INFO_TYPE: Byte = 0
        const val MIN_MAX_LENGTH_TYPE: Byte = 1
        const val PARAM_LENGTH_INFO_TYPE: Byte = 2
        const val STANDARD_LENGTH_TYPE: Byte = 3
    }
}
