// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DiagLayer : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DiagLayer {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun functClasses(j: Int) : dataformat.FunctClass? = functClasses(dataformat.FunctClass(), j)
    fun functClasses(obj: dataformat.FunctClass, j: Int) : dataformat.FunctClass? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val functClassesLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    fun comParamRefs(j: Int) : dataformat.ComParamRef? = comParamRefs(dataformat.ComParamRef(), j)
    fun comParamRefs(obj: dataformat.ComParamRef, j: Int) : dataformat.ComParamRef? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val comParamRefsLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    fun diagServices(j: Int) : dataformat.DiagService? = diagServices(dataformat.DiagService(), j)
    fun diagServices(obj: dataformat.DiagService, j: Int) : dataformat.DiagService? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val diagServicesLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    fun singleEcuJobs(j: Int) : dataformat.SingleEcuJob? = singleEcuJobs(dataformat.SingleEcuJob(), j)
    fun singleEcuJobs(obj: dataformat.SingleEcuJob, j: Int) : dataformat.SingleEcuJob? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val singleEcuJobsLength : Int
        get() {
            val o = __offset(14); return if (o != 0) __vector_len(o) else 0
        }
    fun stateCharts(j: Int) : dataformat.StateChart? = stateCharts(dataformat.StateChart(), j)
    fun stateCharts(obj: dataformat.StateChart, j: Int) : dataformat.StateChart? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val stateChartsLength : Int
        get() {
            val o = __offset(16); return if (o != 0) __vector_len(o) else 0
        }
    fun additionalAudiences(j: Int) : dataformat.AdditionalAudience? = additionalAudiences(dataformat.AdditionalAudience(), j)
    fun additionalAudiences(obj: dataformat.AdditionalAudience, j: Int) : dataformat.AdditionalAudience? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val additionalAudiencesLength : Int
        get() {
            val o = __offset(18); return if (o != 0) __vector_len(o) else 0
        }
    val sdgs : dataformat.SDGS? get() = sdgs(dataformat.SDGS())
    fun sdgs(obj: dataformat.SDGS) : dataformat.SDGS? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsDiagLayer(_bb: ByteBuffer): DiagLayer = getRootAsDiagLayer(_bb, DiagLayer())
        fun getRootAsDiagLayer(_bb: ByteBuffer, obj: DiagLayer): DiagLayer {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDiagLayer(builder: FlatBufferBuilder, shortNameOffset: Int, longNameOffset: Int, functClassesOffset: Int, comParamRefsOffset: Int, diagServicesOffset: Int, singleEcuJobsOffset: Int, stateChartsOffset: Int, additionalAudiencesOffset: Int, sdgsOffset: Int) : Int {
            builder.startTable(9)
            addSdgs(builder, sdgsOffset)
            addAdditionalAudiences(builder, additionalAudiencesOffset)
            addStateCharts(builder, stateChartsOffset)
            addSingleEcuJobs(builder, singleEcuJobsOffset)
            addDiagServices(builder, diagServicesOffset)
            addComParamRefs(builder, comParamRefsOffset)
            addFunctClasses(builder, functClassesOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            return endDiagLayer(builder)
        }
        fun startDiagLayer(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(1, longName, 0)
        fun addFunctClasses(builder: FlatBufferBuilder, functClasses: Int) = builder.addOffset(2, functClasses, 0)
        fun createFunctClassesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startFunctClassesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addComParamRefs(builder: FlatBufferBuilder, comParamRefs: Int) = builder.addOffset(3, comParamRefs, 0)
        fun createComParamRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startComParamRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDiagServices(builder: FlatBufferBuilder, diagServices: Int) = builder.addOffset(4, diagServices, 0)
        fun createDiagServicesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDiagServicesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSingleEcuJobs(builder: FlatBufferBuilder, singleEcuJobs: Int) = builder.addOffset(5, singleEcuJobs, 0)
        fun createSingleEcuJobsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startSingleEcuJobsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addStateCharts(builder: FlatBufferBuilder, stateCharts: Int) = builder.addOffset(6, stateCharts, 0)
        fun createStateChartsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStateChartsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addAdditionalAudiences(builder: FlatBufferBuilder, additionalAudiences: Int) = builder.addOffset(7, additionalAudiences, 0)
        fun createAdditionalAudiencesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startAdditionalAudiencesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(8, sdgs, 0)
        fun endDiagLayer(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
