// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DOP : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DOP {
        __init(_i, _bb)
        return this
    }
    val dopType : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val shortName : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val sdgs : dataformat.SDGS? get() = sdgs(dataformat.SDGS())
    fun sdgs(obj: dataformat.SDGS) : dataformat.SDGS? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val specificDataType : UByte
        get() {
            val o = __offset(10)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun specificData(obj: Table) : Table? {
        val o = __offset(12); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsDOP(_bb: ByteBuffer): DOP = getRootAsDOP(_bb, DOP())
        fun getRootAsDOP(_bb: ByteBuffer, obj: DOP): DOP {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDOP(builder: FlatBufferBuilder, dopType: Byte, shortNameOffset: Int, sdgsOffset: Int, specificDataType: UByte, specificDataOffset: Int) : Int {
            builder.startTable(5)
            addSpecificData(builder, specificDataOffset)
            addSdgs(builder, sdgsOffset)
            addShortName(builder, shortNameOffset)
            addSpecificDataType(builder, specificDataType)
            addDopType(builder, dopType)
            return endDOP(builder)
        }
        fun startDOP(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addDopType(builder: FlatBufferBuilder, dopType: Byte) = builder.addByte(0, dopType, 0)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(1, shortName, 0)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(2, sdgs, 0)
        fun addSpecificDataType(builder: FlatBufferBuilder, specificDataType: UByte) = builder.addByte(3, specificDataType.toByte(), 0)
        fun addSpecificData(builder: FlatBufferBuilder, specificData: Int) = builder.addOffset(4, specificData, 0)
        fun endDOP(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
