// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class DOPType private constructor() {
    companion object {
        const val REGULAR: Byte = 0
        const val ENV_DATA_DESC: Byte = 1
        const val MUX: Byte = 2
        const val DYNAMIC_END_MARKER_FIELD: Byte = 3
        const val DYNAMIC_LENGTH_FIELD: Byte = 4
        const val END_OF_PDU_FIELD: Byte = 5
        const val STATIC_FIELD: Byte = 6
        const val ENV_DATA: Byte = 7
        const val STRUCTURE: Byte = 8
        const val DTC: Byte = 9
    }
}
