// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DTC : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DTC {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val troubleCode : UInt
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val displayTroubleCode : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val displayTroubleCodeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun displayTroubleCodeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val text : dataformat.Text? get() = text(dataformat.Text())
    fun text(obj: dataformat.Text) : dataformat.Text? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val level : UInt?
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else null
        }
    val sdgs : dataformat.SDGS? get() = sdgs(dataformat.SDGS())
    fun sdgs(obj: dataformat.SDGS) : dataformat.SDGS? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val isTemporary : Boolean
        get() {
            val o = __offset(16)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsDTC(_bb: ByteBuffer): DTC = getRootAsDTC(_bb, DTC())
        fun getRootAsDTC(_bb: ByteBuffer, obj: DTC): DTC {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDTC(builder: FlatBufferBuilder, shortNameOffset: Int, troubleCode: UInt, displayTroubleCodeOffset: Int, textOffset: Int, level: UInt?, sdgsOffset: Int, isTemporary: Boolean) : Int {
            builder.startTable(7)
            addSdgs(builder, sdgsOffset)
            level?.run { addLevel(builder, level) }
            addText(builder, textOffset)
            addDisplayTroubleCode(builder, displayTroubleCodeOffset)
            addTroubleCode(builder, troubleCode)
            addShortName(builder, shortNameOffset)
            addIsTemporary(builder, isTemporary)
            return endDTC(builder)
        }
        fun startDTC(builder: FlatBufferBuilder) = builder.startTable(7)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addTroubleCode(builder: FlatBufferBuilder, troubleCode: UInt) = builder.addInt(1, troubleCode.toInt(), 0)
        fun addDisplayTroubleCode(builder: FlatBufferBuilder, displayTroubleCode: Int) = builder.addOffset(2, displayTroubleCode, 0)
        fun addText(builder: FlatBufferBuilder, text: Int) = builder.addOffset(3, text, 0)
        fun addLevel(builder: FlatBufferBuilder, level: UInt) = builder.addInt(4, level.toInt(), 0)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(5, sdgs, 0)
        fun addIsTemporary(builder: FlatBufferBuilder, isTemporary: Boolean) = builder.addBoolean(6, isTemporary, false)
        fun endDTC(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
