// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DTCDOP : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DTCDOP {
        __init(_i, _bb)
        return this
    }
    val diagCodedType : dataformat.DiagCodedType? get() = diagCodedType(dataformat.DiagCodedType())
    fun diagCodedType(obj: dataformat.DiagCodedType) : dataformat.DiagCodedType? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val physicalType : dataformat.PhysicalType? get() = physicalType(dataformat.PhysicalType())
    fun physicalType(obj: dataformat.PhysicalType) : dataformat.PhysicalType? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val compuMethod : dataformat.CompuMethod? get() = compuMethod(dataformat.CompuMethod())
    fun compuMethod(obj: dataformat.CompuMethod) : dataformat.CompuMethod? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun dtcs(j: Int) : dataformat.DTC? = dtcs(dataformat.DTC(), j)
    fun dtcs(obj: dataformat.DTC, j: Int) : dataformat.DTC? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val dtcsLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    val isVisible : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsDTCDOP(_bb: ByteBuffer): DTCDOP = getRootAsDTCDOP(_bb, DTCDOP())
        fun getRootAsDTCDOP(_bb: ByteBuffer, obj: DTCDOP): DTCDOP {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDTCDOP(builder: FlatBufferBuilder, diagCodedTypeOffset: Int, physicalTypeOffset: Int, compuMethodOffset: Int, dtcsOffset: Int, isVisible: Boolean) : Int {
            builder.startTable(5)
            addDtcs(builder, dtcsOffset)
            addCompuMethod(builder, compuMethodOffset)
            addPhysicalType(builder, physicalTypeOffset)
            addDiagCodedType(builder, diagCodedTypeOffset)
            addIsVisible(builder, isVisible)
            return endDTCDOP(builder)
        }
        fun startDTCDOP(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addDiagCodedType(builder: FlatBufferBuilder, diagCodedType: Int) = builder.addOffset(0, diagCodedType, 0)
        fun addPhysicalType(builder: FlatBufferBuilder, physicalType: Int) = builder.addOffset(1, physicalType, 0)
        fun addCompuMethod(builder: FlatBufferBuilder, compuMethod: Int) = builder.addOffset(2, compuMethod, 0)
        fun addDtcs(builder: FlatBufferBuilder, dtcs: Int) = builder.addOffset(3, dtcs, 0)
        fun createDtcsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDtcsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addIsVisible(builder: FlatBufferBuilder, isVisible: Boolean) = builder.addBoolean(4, isVisible, false)
        fun endDTCDOP(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
