// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DynamicLengthField : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DynamicLengthField {
        __init(_i, _bb)
        return this
    }
    val offset : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val field : dataformat.Field? get() = field(dataformat.Field())
    fun field(obj: dataformat.Field) : dataformat.Field? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val determineNumberOfItems : dataformat.DetermineNumberOfItems? get() = determineNumberOfItems(dataformat.DetermineNumberOfItems())
    fun determineNumberOfItems(obj: dataformat.DetermineNumberOfItems) : dataformat.DetermineNumberOfItems? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsDynamicLengthField(_bb: ByteBuffer): DynamicLengthField = getRootAsDynamicLengthField(_bb, DynamicLengthField())
        fun getRootAsDynamicLengthField(_bb: ByteBuffer, obj: DynamicLengthField): DynamicLengthField {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDynamicLengthField(builder: FlatBufferBuilder, offset: UInt, fieldOffset: Int, determineNumberOfItemsOffset: Int) : Int {
            builder.startTable(3)
            addDetermineNumberOfItems(builder, determineNumberOfItemsOffset)
            addField(builder, fieldOffset)
            addOffset(builder, offset)
            return endDynamicLengthField(builder)
        }
        fun startDynamicLengthField(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addOffset(builder: FlatBufferBuilder, offset: UInt) = builder.addInt(0, offset.toInt(), 0)
        fun addField(builder: FlatBufferBuilder, field: Int) = builder.addOffset(1, field, 0)
        fun addDetermineNumberOfItems(builder: FlatBufferBuilder, determineNumberOfItems: Int) = builder.addOffset(2, determineNumberOfItems, 0)
        fun endDynamicLengthField(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
