// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EndOfPduField : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EndOfPduField {
        __init(_i, _bb)
        return this
    }
    val maxNumberOfItems : UInt?
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else null
        }
    val minNumberOfItems : UInt?
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else null
        }
    val field : dataformat.Field? get() = field(dataformat.Field())
    fun field(obj: dataformat.Field) : dataformat.Field? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsEndOfPduField(_bb: ByteBuffer): EndOfPduField = getRootAsEndOfPduField(_bb, EndOfPduField())
        fun getRootAsEndOfPduField(_bb: ByteBuffer, obj: EndOfPduField): EndOfPduField {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEndOfPduField(builder: FlatBufferBuilder, maxNumberOfItems: UInt?, minNumberOfItems: UInt?, fieldOffset: Int) : Int {
            builder.startTable(3)
            addField(builder, fieldOffset)
            minNumberOfItems?.run { addMinNumberOfItems(builder, minNumberOfItems) }
            maxNumberOfItems?.run { addMaxNumberOfItems(builder, maxNumberOfItems) }
            return endEndOfPduField(builder)
        }
        fun startEndOfPduField(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addMaxNumberOfItems(builder: FlatBufferBuilder, maxNumberOfItems: UInt) = builder.addInt(0, maxNumberOfItems.toInt(), 0)
        fun addMinNumberOfItems(builder: FlatBufferBuilder, minNumberOfItems: UInt) = builder.addInt(1, minNumberOfItems.toInt(), 0)
        fun addField(builder: FlatBufferBuilder, field: Int) = builder.addOffset(2, field, 0)
        fun endEndOfPduField(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
