// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EnvDataDesc : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EnvDataDesc {
        __init(_i, _bb)
        return this
    }
    val paramShortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val paramShortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun paramShortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val paramPathShortName : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val paramPathShortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun paramPathShortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    fun envDatas(j: Int) : dataformat.DOP? = envDatas(dataformat.DOP(), j)
    fun envDatas(obj: dataformat.DOP, j: Int) : dataformat.DOP? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val envDatasLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsEnvDataDesc(_bb: ByteBuffer): EnvDataDesc = getRootAsEnvDataDesc(_bb, EnvDataDesc())
        fun getRootAsEnvDataDesc(_bb: ByteBuffer, obj: EnvDataDesc): EnvDataDesc {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEnvDataDesc(builder: FlatBufferBuilder, paramShortNameOffset: Int, paramPathShortNameOffset: Int, envDatasOffset: Int) : Int {
            builder.startTable(3)
            addEnvDatas(builder, envDatasOffset)
            addParamPathShortName(builder, paramPathShortNameOffset)
            addParamShortName(builder, paramShortNameOffset)
            return endEnvDataDesc(builder)
        }
        fun startEnvDataDesc(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addParamShortName(builder: FlatBufferBuilder, paramShortName: Int) = builder.addOffset(0, paramShortName, 0)
        fun addParamPathShortName(builder: FlatBufferBuilder, paramPathShortName: Int) = builder.addOffset(1, paramPathShortName, 0)
        fun addEnvDatas(builder: FlatBufferBuilder, envDatas: Int) = builder.addOffset(2, envDatas, 0)
        fun createEnvDatasVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startEnvDatasVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endEnvDataDesc(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
