// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EnvData : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EnvData {
        __init(_i, _bb)
        return this
    }
    fun dtcValues(j: Int) : UInt {
        val o = __offset(4)
        return if (o != 0) {
            bb.getInt(__vector(o) + j * 4).toUInt()
        } else {
            0u
        }
    }
    val dtcValuesLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val dtcValuesAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 4)
    fun dtcValuesInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 4)
    fun params(j: Int) : dataformat.Param? = params(dataformat.Param(), j)
    fun params(obj: dataformat.Param, j: Int) : dataformat.Param? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val paramsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsEnvData(_bb: ByteBuffer): EnvData = getRootAsEnvData(_bb, EnvData())
        fun getRootAsEnvData(_bb: ByteBuffer, obj: EnvData): EnvData {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEnvData(builder: FlatBufferBuilder, dtcValuesOffset: Int, paramsOffset: Int) : Int {
            builder.startTable(2)
            addParams(builder, paramsOffset)
            addDtcValues(builder, dtcValuesOffset)
            return endEnvData(builder)
        }
        fun startEnvData(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addDtcValues(builder: FlatBufferBuilder, dtcValues: Int) = builder.addOffset(0, dtcValues, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createDtcValuesVector(builder: FlatBufferBuilder, data: UIntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addInt(data[i].toInt())
            }
            return builder.endVector()
        }
        fun startDtcValuesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addParams(builder: FlatBufferBuilder, params: Int) = builder.addOffset(1, params, 0)
        fun createParamsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startParamsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endEnvData(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
