// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class FeatureFlag private constructor() {
    companion object {
        const val RESERVED: Byte = 0
    }
}
