// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Field : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Field {
        __init(_i, _bb)
        return this
    }
    val basicStructure : dataformat.DOP? get() = basicStructure(dataformat.DOP())
    fun basicStructure(obj: dataformat.DOP) : dataformat.DOP? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val envDataDesc : dataformat.DOP? get() = envDataDesc(dataformat.DOP())
    fun envDataDesc(obj: dataformat.DOP) : dataformat.DOP? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val isVisible : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else true
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsField(_bb: ByteBuffer): Field = getRootAsField(_bb, Field())
        fun getRootAsField(_bb: ByteBuffer, obj: Field): Field {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createField(builder: FlatBufferBuilder, basicStructureOffset: Int, envDataDescOffset: Int, isVisible: Boolean) : Int {
            builder.startTable(3)
            addEnvDataDesc(builder, envDataDescOffset)
            addBasicStructure(builder, basicStructureOffset)
            addIsVisible(builder, isVisible)
            return endField(builder)
        }
        fun startField(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addBasicStructure(builder: FlatBufferBuilder, basicStructure: Int) = builder.addOffset(0, basicStructure, 0)
        fun addEnvDataDesc(builder: FlatBufferBuilder, envDataDesc: Int) = builder.addOffset(1, envDataDesc, 0)
        fun addIsVisible(builder: FlatBufferBuilder, isVisible: Boolean) = builder.addBoolean(2, isVisible, true)
        fun endField(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
