// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FunctionalGroup : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FunctionalGroup {
        __init(_i, _bb)
        return this
    }
    val diagLayer : dataformat.DiagLayer? get() = diagLayer(dataformat.DiagLayer())
    fun diagLayer(obj: dataformat.DiagLayer) : dataformat.DiagLayer? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun parentRefs(j: Int) : dataformat.ParentRef? = parentRefs(dataformat.ParentRef(), j)
    fun parentRefs(obj: dataformat.ParentRef, j: Int) : dataformat.ParentRef? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val parentRefsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsFunctionalGroup(_bb: ByteBuffer): FunctionalGroup = getRootAsFunctionalGroup(_bb, FunctionalGroup())
        fun getRootAsFunctionalGroup(_bb: ByteBuffer, obj: FunctionalGroup): FunctionalGroup {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFunctionalGroup(builder: FlatBufferBuilder, diagLayerOffset: Int, parentRefsOffset: Int) : Int {
            builder.startTable(2)
            addParentRefs(builder, parentRefsOffset)
            addDiagLayer(builder, diagLayerOffset)
            return endFunctionalGroup(builder)
        }
        fun startFunctionalGroup(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addDiagLayer(builder: FlatBufferBuilder, diagLayer: Int) = builder.addOffset(0, diagLayer, 0)
        fun addParentRefs(builder: FlatBufferBuilder, parentRefs: Int) = builder.addOffset(1, parentRefs, 0)
        fun createParentRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startParentRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endFunctionalGroup(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
