// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FunctClass : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FunctClass {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsFunctClass(_bb: ByteBuffer): FunctClass = getRootAsFunctClass(_bb, FunctClass())
        fun getRootAsFunctClass(_bb: ByteBuffer, obj: FunctClass): FunctClass {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFunctClass(builder: FlatBufferBuilder, shortNameOffset: Int) : Int {
            builder.startTable(1)
            addShortName(builder, shortNameOffset)
            return endFunctClass(builder)
        }
        fun startFunctClass(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun endFunctClass(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
