// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class InternalConstr : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : InternalConstr {
        __init(_i, _bb)
        return this
    }
    val lowerLimit : dataformat.Limit? get() = lowerLimit(dataformat.Limit())
    fun lowerLimit(obj: dataformat.Limit) : dataformat.Limit? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val upperLimit : dataformat.Limit? get() = upperLimit(dataformat.Limit())
    fun upperLimit(obj: dataformat.Limit) : dataformat.Limit? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun scaleConstr(j: Int) : dataformat.ScaleConstr? = scaleConstr(dataformat.ScaleConstr(), j)
    fun scaleConstr(obj: dataformat.ScaleConstr, j: Int) : dataformat.ScaleConstr? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val scaleConstrLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsInternalConstr(_bb: ByteBuffer): InternalConstr = getRootAsInternalConstr(_bb, InternalConstr())
        fun getRootAsInternalConstr(_bb: ByteBuffer, obj: InternalConstr): InternalConstr {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createInternalConstr(builder: FlatBufferBuilder, lowerLimitOffset: Int, upperLimitOffset: Int, scaleConstrOffset: Int) : Int {
            builder.startTable(3)
            addScaleConstr(builder, scaleConstrOffset)
            addUpperLimit(builder, upperLimitOffset)
            addLowerLimit(builder, lowerLimitOffset)
            return endInternalConstr(builder)
        }
        fun startInternalConstr(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addLowerLimit(builder: FlatBufferBuilder, lowerLimit: Int) = builder.addOffset(0, lowerLimit, 0)
        fun addUpperLimit(builder: FlatBufferBuilder, upperLimit: Int) = builder.addOffset(1, upperLimit, 0)
        fun addScaleConstr(builder: FlatBufferBuilder, scaleConstr: Int) = builder.addOffset(2, scaleConstr, 0)
        fun createScaleConstrVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startScaleConstrVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endInternalConstr(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
