// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class IntervalType private constructor() {
    companion object {
        const val OPEN: Byte = 0
        const val CLOSED: Byte = 1
        const val INFINITE: Byte = 2
    }
}
