// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class JobParam : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : JobParam {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val physicalDefaultValue : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val physicalDefaultValueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun physicalDefaultValueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val dopBase : dataformat.DOP? get() = dopBase(dataformat.DOP())
    fun dopBase(obj: dataformat.DOP) : dataformat.DOP? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val semantic : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val semanticAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun semanticInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsJobParam(_bb: ByteBuffer): JobParam = getRootAsJobParam(_bb, JobParam())
        fun getRootAsJobParam(_bb: ByteBuffer, obj: JobParam): JobParam {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createJobParam(builder: FlatBufferBuilder, shortNameOffset: Int, longNameOffset: Int, physicalDefaultValueOffset: Int, dopBaseOffset: Int, semanticOffset: Int) : Int {
            builder.startTable(5)
            addSemantic(builder, semanticOffset)
            addDopBase(builder, dopBaseOffset)
            addPhysicalDefaultValue(builder, physicalDefaultValueOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            return endJobParam(builder)
        }
        fun startJobParam(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(1, longName, 0)
        fun addPhysicalDefaultValue(builder: FlatBufferBuilder, physicalDefaultValue: Int) = builder.addOffset(2, physicalDefaultValue, 0)
        fun addDopBase(builder: FlatBufferBuilder, dopBase: Int) = builder.addOffset(3, dopBase, 0)
        fun addSemantic(builder: FlatBufferBuilder, semantic: Int) = builder.addOffset(4, semantic, 0)
        fun endJobParam(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
