// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Library : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Library {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val codeFile : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val codeFileAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun codeFileInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val encryption : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val encryptionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun encryptionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val syntax : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val syntaxAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun syntaxInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val entryPoint : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val entryPointAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun entryPointInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsLibrary(_bb: ByteBuffer): Library = getRootAsLibrary(_bb, Library())
        fun getRootAsLibrary(_bb: ByteBuffer, obj: Library): Library {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createLibrary(builder: FlatBufferBuilder, shortNameOffset: Int, longNameOffset: Int, codeFileOffset: Int, encryptionOffset: Int, syntaxOffset: Int, entryPointOffset: Int) : Int {
            builder.startTable(6)
            addEntryPoint(builder, entryPointOffset)
            addSyntax(builder, syntaxOffset)
            addEncryption(builder, encryptionOffset)
            addCodeFile(builder, codeFileOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            return endLibrary(builder)
        }
        fun startLibrary(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(1, longName, 0)
        fun addCodeFile(builder: FlatBufferBuilder, codeFile: Int) = builder.addOffset(2, codeFile, 0)
        fun addEncryption(builder: FlatBufferBuilder, encryption: Int) = builder.addOffset(3, encryption, 0)
        fun addSyntax(builder: FlatBufferBuilder, syntax: Int) = builder.addOffset(4, syntax, 0)
        fun addEntryPoint(builder: FlatBufferBuilder, entryPoint: Int) = builder.addOffset(5, entryPoint, 0)
        fun endLibrary(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
