// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MatchingRequestParam : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MatchingRequestParam {
        __init(_i, _bb)
        return this
    }
    val requestBytePos : Int
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    val byteLength : UInt
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsMatchingRequestParam(_bb: ByteBuffer): MatchingRequestParam = getRootAsMatchingRequestParam(_bb, MatchingRequestParam())
        fun getRootAsMatchingRequestParam(_bb: ByteBuffer, obj: MatchingRequestParam): MatchingRequestParam {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMatchingRequestParam(builder: FlatBufferBuilder, requestBytePos: Int, byteLength: UInt) : Int {
            builder.startTable(2)
            addByteLength(builder, byteLength)
            addRequestBytePos(builder, requestBytePos)
            return endMatchingRequestParam(builder)
        }
        fun startMatchingRequestParam(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addRequestBytePos(builder: FlatBufferBuilder, requestBytePos: Int) = builder.addInt(0, requestBytePos, 0)
        fun addByteLength(builder: FlatBufferBuilder, byteLength: UInt) = builder.addInt(1, byteLength.toInt(), 0)
        fun endMatchingRequestParam(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
