// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MatchingParameter : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MatchingParameter {
        __init(_i, _bb)
        return this
    }
    val expectedValue : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val expectedValueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun expectedValueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val diagService : dataformat.DiagService? get() = diagService(dataformat.DiagService())
    fun diagService(obj: dataformat.DiagService) : dataformat.DiagService? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val outParam : dataformat.Param? get() = outParam(dataformat.Param())
    fun outParam(obj: dataformat.Param) : dataformat.Param? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val usePhysicalAddressing : Boolean?
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else null
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsMatchingParameter(_bb: ByteBuffer): MatchingParameter = getRootAsMatchingParameter(_bb, MatchingParameter())
        fun getRootAsMatchingParameter(_bb: ByteBuffer, obj: MatchingParameter): MatchingParameter {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMatchingParameter(builder: FlatBufferBuilder, expectedValueOffset: Int, diagServiceOffset: Int, outParamOffset: Int, usePhysicalAddressing: Boolean?) : Int {
            builder.startTable(4)
            addOutParam(builder, outParamOffset)
            addDiagService(builder, diagServiceOffset)
            addExpectedValue(builder, expectedValueOffset)
            usePhysicalAddressing?.run { addUsePhysicalAddressing(builder, usePhysicalAddressing) }
            return endMatchingParameter(builder)
        }
        fun startMatchingParameter(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addExpectedValue(builder: FlatBufferBuilder, expectedValue: Int) = builder.addOffset(0, expectedValue, 0)
        fun addDiagService(builder: FlatBufferBuilder, diagService: Int) = builder.addOffset(1, diagService, 0)
        fun addOutParam(builder: FlatBufferBuilder, outParam: Int) = builder.addOffset(2, outParam, 0)
        fun addUsePhysicalAddressing(builder: FlatBufferBuilder, usePhysicalAddressing: Boolean) = builder.addBoolean(3, usePhysicalAddressing, false)
        fun endMatchingParameter(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
