// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MinMaxLengthType : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MinMaxLengthType {
        __init(_i, _bb)
        return this
    }
    val minLength : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val maxLength : UInt?
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else null
        }
    val termination : Byte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsMinMaxLengthType(_bb: ByteBuffer): MinMaxLengthType = getRootAsMinMaxLengthType(_bb, MinMaxLengthType())
        fun getRootAsMinMaxLengthType(_bb: ByteBuffer, obj: MinMaxLengthType): MinMaxLengthType {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMinMaxLengthType(builder: FlatBufferBuilder, minLength: UInt, maxLength: UInt?, termination: Byte) : Int {
            builder.startTable(3)
            maxLength?.run { addMaxLength(builder, maxLength) }
            addMinLength(builder, minLength)
            addTermination(builder, termination)
            return endMinMaxLengthType(builder)
        }
        fun startMinMaxLengthType(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addMinLength(builder: FlatBufferBuilder, minLength: UInt) = builder.addInt(0, minLength.toInt(), 0)
        fun addMaxLength(builder: FlatBufferBuilder, maxLength: UInt) = builder.addInt(1, maxLength.toInt(), 0)
        fun addTermination(builder: FlatBufferBuilder, termination: Byte) = builder.addByte(2, termination, 0)
        fun endMinMaxLengthType(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
