// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MUXDOP : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MUXDOP {
        __init(_i, _bb)
        return this
    }
    val bytePosition : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val switchKey : dataformat.SwitchKey? get() = switchKey(dataformat.SwitchKey())
    fun switchKey(obj: dataformat.SwitchKey) : dataformat.SwitchKey? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val defaultCase : dataformat.DefaultCase? get() = defaultCase(dataformat.DefaultCase())
    fun defaultCase(obj: dataformat.DefaultCase) : dataformat.DefaultCase? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun cases(j: Int) : dataformat.Case? = cases(dataformat.Case(), j)
    fun cases(obj: dataformat.Case, j: Int) : dataformat.Case? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val casesLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    val isVisible : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsMUXDOP(_bb: ByteBuffer): MUXDOP = getRootAsMUXDOP(_bb, MUXDOP())
        fun getRootAsMUXDOP(_bb: ByteBuffer, obj: MUXDOP): MUXDOP {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMUXDOP(builder: FlatBufferBuilder, bytePosition: UInt, switchKeyOffset: Int, defaultCaseOffset: Int, casesOffset: Int, isVisible: Boolean) : Int {
            builder.startTable(5)
            addCases(builder, casesOffset)
            addDefaultCase(builder, defaultCaseOffset)
            addSwitchKey(builder, switchKeyOffset)
            addBytePosition(builder, bytePosition)
            addIsVisible(builder, isVisible)
            return endMUXDOP(builder)
        }
        fun startMUXDOP(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addBytePosition(builder: FlatBufferBuilder, bytePosition: UInt) = builder.addInt(0, bytePosition.toInt(), 0)
        fun addSwitchKey(builder: FlatBufferBuilder, switchKey: Int) = builder.addOffset(1, switchKey, 0)
        fun addDefaultCase(builder: FlatBufferBuilder, defaultCase: Int) = builder.addOffset(2, defaultCase, 0)
        fun addCases(builder: FlatBufferBuilder, cases: Int) = builder.addOffset(3, cases, 0)
        fun createCasesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startCasesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addIsVisible(builder: FlatBufferBuilder, isVisible: Boolean) = builder.addBoolean(4, isVisible, false)
        fun endMUXDOP(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
