// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class NormalDOP : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : NormalDOP {
        __init(_i, _bb)
        return this
    }
    val compuMethod : dataformat.CompuMethod? get() = compuMethod(dataformat.CompuMethod())
    fun compuMethod(obj: dataformat.CompuMethod) : dataformat.CompuMethod? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val diagCodedType : dataformat.DiagCodedType? get() = diagCodedType(dataformat.DiagCodedType())
    fun diagCodedType(obj: dataformat.DiagCodedType) : dataformat.DiagCodedType? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val physicalType : dataformat.PhysicalType? get() = physicalType(dataformat.PhysicalType())
    fun physicalType(obj: dataformat.PhysicalType) : dataformat.PhysicalType? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val internalConstr : dataformat.InternalConstr? get() = internalConstr(dataformat.InternalConstr())
    fun internalConstr(obj: dataformat.InternalConstr) : dataformat.InternalConstr? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val unitRef : dataformat.Unit? get() = unitRef(dataformat.Unit())
    fun unitRef(obj: dataformat.Unit) : dataformat.Unit? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val physConstr : dataformat.InternalConstr? get() = physConstr(dataformat.InternalConstr())
    fun physConstr(obj: dataformat.InternalConstr) : dataformat.InternalConstr? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsNormalDOP(_bb: ByteBuffer): NormalDOP = getRootAsNormalDOP(_bb, NormalDOP())
        fun getRootAsNormalDOP(_bb: ByteBuffer, obj: NormalDOP): NormalDOP {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createNormalDOP(builder: FlatBufferBuilder, compuMethodOffset: Int, diagCodedTypeOffset: Int, physicalTypeOffset: Int, internalConstrOffset: Int, unitRefOffset: Int, physConstrOffset: Int) : Int {
            builder.startTable(6)
            addPhysConstr(builder, physConstrOffset)
            addUnitRef(builder, unitRefOffset)
            addInternalConstr(builder, internalConstrOffset)
            addPhysicalType(builder, physicalTypeOffset)
            addDiagCodedType(builder, diagCodedTypeOffset)
            addCompuMethod(builder, compuMethodOffset)
            return endNormalDOP(builder)
        }
        fun startNormalDOP(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addCompuMethod(builder: FlatBufferBuilder, compuMethod: Int) = builder.addOffset(0, compuMethod, 0)
        fun addDiagCodedType(builder: FlatBufferBuilder, diagCodedType: Int) = builder.addOffset(1, diagCodedType, 0)
        fun addPhysicalType(builder: FlatBufferBuilder, physicalType: Int) = builder.addOffset(2, physicalType, 0)
        fun addInternalConstr(builder: FlatBufferBuilder, internalConstr: Int) = builder.addOffset(3, internalConstr, 0)
        fun addUnitRef(builder: FlatBufferBuilder, unitRef: Int) = builder.addOffset(4, unitRef, 0)
        fun addPhysConstr(builder: FlatBufferBuilder, physConstr: Int) = builder.addOffset(5, physConstr, 0)
        fun endNormalDOP(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
