// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class NrcConst : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : NrcConst {
        __init(_i, _bb)
        return this
    }
    fun codedValues(j: Int) : String? {
        val o = __offset(4)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val codedValuesLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val diagCodedType : dataformat.DiagCodedType? get() = diagCodedType(dataformat.DiagCodedType())
    fun diagCodedType(obj: dataformat.DiagCodedType) : dataformat.DiagCodedType? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsNrcConst(_bb: ByteBuffer): NrcConst = getRootAsNrcConst(_bb, NrcConst())
        fun getRootAsNrcConst(_bb: ByteBuffer, obj: NrcConst): NrcConst {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createNrcConst(builder: FlatBufferBuilder, codedValuesOffset: Int, diagCodedTypeOffset: Int) : Int {
            builder.startTable(2)
            addDiagCodedType(builder, diagCodedTypeOffset)
            addCodedValues(builder, codedValuesOffset)
            return endNrcConst(builder)
        }
        fun startNrcConst(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addCodedValues(builder: FlatBufferBuilder, codedValues: Int) = builder.addOffset(0, codedValues, 0)
        fun createCodedValuesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startCodedValuesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDiagCodedType(builder: FlatBufferBuilder, diagCodedType: Int) = builder.addOffset(1, diagCodedType, 0)
        fun endNrcConst(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
