// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class ParamSpecificData private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val CodedConst: UByte = 1u
        const val Dynamic: UByte = 2u
        const val MatchingRequestParam: UByte = 3u
        const val NrcConst: UByte = 4u
        const val PhysConst: UByte = 5u
        const val Reserved: UByte = 6u
        const val Value: UByte = 7u
        const val TableEntry: UByte = 8u
        const val TableKey: UByte = 9u
        const val TableStruct: UByte = 10u
        const val System: UByte = 11u
        const val LengthKeyRef: UByte = 12u
    }
}
