// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class ParamType private constructor() {
    companion object {
        const val CODED_CONST: Byte = 0
        const val DYNAMIC: Byte = 1
        const val LENGTH_KEY: Byte = 2
        const val MATCHING_REQUEST_PARAM: Byte = 3
        const val NRC_CONST: Byte = 4
        const val PHYS_CONST: Byte = 5
        const val RESERVED: Byte = 6
        const val SYSTEM: Byte = 7
        const val TABLE_ENTRY: Byte = 8
        const val TABLE_KEY: Byte = 9
        const val TABLE_STRUCT: Byte = 10
        const val VALUE: Byte = 11
    }
}
