// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Param : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Param {
        __init(_i, _bb)
        return this
    }
    val id : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val paramType : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val shortName : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val semantic : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val semanticAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun semanticInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val sdgs : dataformat.SDGS? get() = sdgs(dataformat.SDGS())
    fun sdgs(obj: dataformat.SDGS) : dataformat.SDGS? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val physicalDefaultValue : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val physicalDefaultValueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun physicalDefaultValueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val bytePosition : UInt?
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else null
        }
    val bitPosition : UInt?
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else null
        }
    val specificDataType : UByte
        get() {
            val o = __offset(20)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun specificData(obj: Table) : Table? {
        val o = __offset(22); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsParam(_bb: ByteBuffer): Param = getRootAsParam(_bb, Param())
        fun getRootAsParam(_bb: ByteBuffer, obj: Param): Param {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createParam(builder: FlatBufferBuilder, id: UInt, paramType: Byte, shortNameOffset: Int, semanticOffset: Int, sdgsOffset: Int, physicalDefaultValueOffset: Int, bytePosition: UInt?, bitPosition: UInt?, specificDataType: UByte, specificDataOffset: Int) : Int {
            builder.startTable(10)
            addSpecificData(builder, specificDataOffset)
            bitPosition?.run { addBitPosition(builder, bitPosition) }
            bytePosition?.run { addBytePosition(builder, bytePosition) }
            addPhysicalDefaultValue(builder, physicalDefaultValueOffset)
            addSdgs(builder, sdgsOffset)
            addSemantic(builder, semanticOffset)
            addShortName(builder, shortNameOffset)
            addId(builder, id)
            addSpecificDataType(builder, specificDataType)
            addParamType(builder, paramType)
            return endParam(builder)
        }
        fun startParam(builder: FlatBufferBuilder) = builder.startTable(10)
        fun addId(builder: FlatBufferBuilder, id: UInt) = builder.addInt(0, id.toInt(), 0)
        fun addParamType(builder: FlatBufferBuilder, paramType: Byte) = builder.addByte(1, paramType, 0)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(2, shortName, 0)
        fun addSemantic(builder: FlatBufferBuilder, semantic: Int) = builder.addOffset(3, semantic, 0)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(4, sdgs, 0)
        fun addPhysicalDefaultValue(builder: FlatBufferBuilder, physicalDefaultValue: Int) = builder.addOffset(5, physicalDefaultValue, 0)
        fun addBytePosition(builder: FlatBufferBuilder, bytePosition: UInt) = builder.addInt(6, bytePosition.toInt(), 0)
        fun addBitPosition(builder: FlatBufferBuilder, bitPosition: UInt) = builder.addInt(7, bitPosition.toInt(), 0)
        fun addSpecificDataType(builder: FlatBufferBuilder, specificDataType: UByte) = builder.addByte(8, specificDataType.toByte(), 0)
        fun addSpecificData(builder: FlatBufferBuilder, specificData: Int) = builder.addOffset(9, specificData, 0)
        fun endParam(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
