// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ParentRef : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ParentRef {
        __init(_i, _bb)
        return this
    }
    val refType : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun ref(obj: Table) : Table? {
        val o = __offset(6); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    fun notInheritedDiagCommShortNames(j: Int) : String? {
        val o = __offset(8)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val notInheritedDiagCommShortNamesLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    fun notInheritedVariablesShortNames(j: Int) : String? {
        val o = __offset(10)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val notInheritedVariablesShortNamesLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    fun notInheritedDopsShortNames(j: Int) : String? {
        val o = __offset(12)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val notInheritedDopsShortNamesLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    fun notInheritedTablesShortNames(j: Int) : String? {
        val o = __offset(14)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val notInheritedTablesShortNamesLength : Int
        get() {
            val o = __offset(14); return if (o != 0) __vector_len(o) else 0
        }
    fun notInheritedGlobalNegResponsesShortNames(j: Int) : String? {
        val o = __offset(16)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val notInheritedGlobalNegResponsesShortNamesLength : Int
        get() {
            val o = __offset(16); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsParentRef(_bb: ByteBuffer): ParentRef = getRootAsParentRef(_bb, ParentRef())
        fun getRootAsParentRef(_bb: ByteBuffer, obj: ParentRef): ParentRef {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createParentRef(builder: FlatBufferBuilder, refType: UByte, refOffset: Int, notInheritedDiagCommShortNamesOffset: Int, notInheritedVariablesShortNamesOffset: Int, notInheritedDopsShortNamesOffset: Int, notInheritedTablesShortNamesOffset: Int, notInheritedGlobalNegResponsesShortNamesOffset: Int) : Int {
            builder.startTable(7)
            addNotInheritedGlobalNegResponsesShortNames(builder, notInheritedGlobalNegResponsesShortNamesOffset)
            addNotInheritedTablesShortNames(builder, notInheritedTablesShortNamesOffset)
            addNotInheritedDopsShortNames(builder, notInheritedDopsShortNamesOffset)
            addNotInheritedVariablesShortNames(builder, notInheritedVariablesShortNamesOffset)
            addNotInheritedDiagCommShortNames(builder, notInheritedDiagCommShortNamesOffset)
            addRef(builder, refOffset)
            addRefType(builder, refType)
            return endParentRef(builder)
        }
        fun startParentRef(builder: FlatBufferBuilder) = builder.startTable(7)
        fun addRefType(builder: FlatBufferBuilder, refType: UByte) = builder.addByte(0, refType.toByte(), 0)
        fun addRef(builder: FlatBufferBuilder, ref: Int) = builder.addOffset(1, ref, 0)
        fun addNotInheritedDiagCommShortNames(builder: FlatBufferBuilder, notInheritedDiagCommShortNames: Int) = builder.addOffset(2, notInheritedDiagCommShortNames, 0)
        fun createNotInheritedDiagCommShortNamesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startNotInheritedDiagCommShortNamesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addNotInheritedVariablesShortNames(builder: FlatBufferBuilder, notInheritedVariablesShortNames: Int) = builder.addOffset(3, notInheritedVariablesShortNames, 0)
        fun createNotInheritedVariablesShortNamesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startNotInheritedVariablesShortNamesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addNotInheritedDopsShortNames(builder: FlatBufferBuilder, notInheritedDopsShortNames: Int) = builder.addOffset(4, notInheritedDopsShortNames, 0)
        fun createNotInheritedDopsShortNamesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startNotInheritedDopsShortNamesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addNotInheritedTablesShortNames(builder: FlatBufferBuilder, notInheritedTablesShortNames: Int) = builder.addOffset(5, notInheritedTablesShortNames, 0)
        fun createNotInheritedTablesShortNamesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startNotInheritedTablesShortNamesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addNotInheritedGlobalNegResponsesShortNames(builder: FlatBufferBuilder, notInheritedGlobalNegResponsesShortNames: Int) = builder.addOffset(6, notInheritedGlobalNegResponsesShortNames, 0)
        fun createNotInheritedGlobalNegResponsesShortNamesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startNotInheritedGlobalNegResponsesShortNamesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endParentRef(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
