// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class ParentRefType private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val Variant: UByte = 1u
        const val Protocol: UByte = 2u
        const val FunctionalGroup: UByte = 3u
        const val TableDop: UByte = 4u
        const val EcuSharedData: UByte = 5u
    }
}
