// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PhysicalType : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PhysicalType {
        __init(_i, _bb)
        return this
    }
    val precision : UInt?
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else null
        }
    val baseDataType : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val displayRadix : Byte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsPhysicalType(_bb: ByteBuffer): PhysicalType = getRootAsPhysicalType(_bb, PhysicalType())
        fun getRootAsPhysicalType(_bb: ByteBuffer, obj: PhysicalType): PhysicalType {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPhysicalType(builder: FlatBufferBuilder, precision: UInt?, baseDataType: Byte, displayRadix: Byte) : Int {
            builder.startTable(3)
            precision?.run { addPrecision(builder, precision) }
            addDisplayRadix(builder, displayRadix)
            addBaseDataType(builder, baseDataType)
            return endPhysicalType(builder)
        }
        fun startPhysicalType(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addPrecision(builder: FlatBufferBuilder, precision: UInt) = builder.addInt(0, precision.toInt(), 0)
        fun addBaseDataType(builder: FlatBufferBuilder, baseDataType: Byte) = builder.addByte(1, baseDataType, 0)
        fun addDisplayRadix(builder: FlatBufferBuilder, displayRadix: Byte) = builder.addByte(2, displayRadix, 0)
        fun endPhysicalType(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
