// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PhysicalDimension : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PhysicalDimension {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val lengthExp : Int?
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos) else null
        }
    val massExp : Int?
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getInt(o + bb_pos) else null
        }
    val timeExp : Int?
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getInt(o + bb_pos) else null
        }
    val currentExp : Int?
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getInt(o + bb_pos) else null
        }
    val temperatureExp : Int?
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getInt(o + bb_pos) else null
        }
    val molarAmountExp : Int?
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getInt(o + bb_pos) else null
        }
    val luminousIntensityExp : Int?
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getInt(o + bb_pos) else null
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsPhysicalDimension(_bb: ByteBuffer): PhysicalDimension = getRootAsPhysicalDimension(_bb, PhysicalDimension())
        fun getRootAsPhysicalDimension(_bb: ByteBuffer, obj: PhysicalDimension): PhysicalDimension {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPhysicalDimension(builder: FlatBufferBuilder, shortNameOffset: Int, longNameOffset: Int, lengthExp: Int?, massExp: Int?, timeExp: Int?, currentExp: Int?, temperatureExp: Int?, molarAmountExp: Int?, luminousIntensityExp: Int?) : Int {
            builder.startTable(9)
            luminousIntensityExp?.run { addLuminousIntensityExp(builder, luminousIntensityExp) }
            molarAmountExp?.run { addMolarAmountExp(builder, molarAmountExp) }
            temperatureExp?.run { addTemperatureExp(builder, temperatureExp) }
            currentExp?.run { addCurrentExp(builder, currentExp) }
            timeExp?.run { addTimeExp(builder, timeExp) }
            massExp?.run { addMassExp(builder, massExp) }
            lengthExp?.run { addLengthExp(builder, lengthExp) }
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            return endPhysicalDimension(builder)
        }
        fun startPhysicalDimension(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(1, longName, 0)
        fun addLengthExp(builder: FlatBufferBuilder, lengthExp: Int) = builder.addInt(2, lengthExp, 0)
        fun addMassExp(builder: FlatBufferBuilder, massExp: Int) = builder.addInt(3, massExp, 0)
        fun addTimeExp(builder: FlatBufferBuilder, timeExp: Int) = builder.addInt(4, timeExp, 0)
        fun addCurrentExp(builder: FlatBufferBuilder, currentExp: Int) = builder.addInt(5, currentExp, 0)
        fun addTemperatureExp(builder: FlatBufferBuilder, temperatureExp: Int) = builder.addInt(6, temperatureExp, 0)
        fun addMolarAmountExp(builder: FlatBufferBuilder, molarAmountExp: Int) = builder.addInt(7, molarAmountExp, 0)
        fun addLuminousIntensityExp(builder: FlatBufferBuilder, luminousIntensityExp: Int) = builder.addInt(8, luminousIntensityExp, 0)
        fun endPhysicalDimension(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
