// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PreConditionStateRef : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PreConditionStateRef {
        __init(_i, _bb)
        return this
    }
    val value : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val valueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun valueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val inParamIfShortName : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val inParamIfShortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun inParamIfShortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val inParamPathShortName : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val inParamPathShortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun inParamPathShortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val state : dataformat.State? get() = state(dataformat.State())
    fun state(obj: dataformat.State) : dataformat.State? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsPreConditionStateRef(_bb: ByteBuffer): PreConditionStateRef = getRootAsPreConditionStateRef(_bb, PreConditionStateRef())
        fun getRootAsPreConditionStateRef(_bb: ByteBuffer, obj: PreConditionStateRef): PreConditionStateRef {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPreConditionStateRef(builder: FlatBufferBuilder, valueOffset: Int, inParamIfShortNameOffset: Int, inParamPathShortNameOffset: Int, stateOffset: Int) : Int {
            builder.startTable(4)
            addState(builder, stateOffset)
            addInParamPathShortName(builder, inParamPathShortNameOffset)
            addInParamIfShortName(builder, inParamIfShortNameOffset)
            addValue(builder, valueOffset)
            return endPreConditionStateRef(builder)
        }
        fun startPreConditionStateRef(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addValue(builder: FlatBufferBuilder, value: Int) = builder.addOffset(0, value, 0)
        fun addInParamIfShortName(builder: FlatBufferBuilder, inParamIfShortName: Int) = builder.addOffset(1, inParamIfShortName, 0)
        fun addInParamPathShortName(builder: FlatBufferBuilder, inParamPathShortName: Int) = builder.addOffset(2, inParamPathShortName, 0)
        fun addState(builder: FlatBufferBuilder, state: Int) = builder.addOffset(3, state, 0)
        fun endPreConditionStateRef(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
