// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ProgCode : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ProgCode {
        __init(_i, _bb)
        return this
    }
    val codeFile : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val codeFileAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun codeFileInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val encryption : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val encryptionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun encryptionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val syntax : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val syntaxAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun syntaxInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val revision : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val revisionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun revisionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val entrypoint : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val entrypointAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun entrypointInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    fun library(j: Int) : dataformat.Library? = library(dataformat.Library(), j)
    fun library(obj: dataformat.Library, j: Int) : dataformat.Library? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val libraryLength : Int
        get() {
            val o = __offset(14); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsProgCode(_bb: ByteBuffer): ProgCode = getRootAsProgCode(_bb, ProgCode())
        fun getRootAsProgCode(_bb: ByteBuffer, obj: ProgCode): ProgCode {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createProgCode(builder: FlatBufferBuilder, codeFileOffset: Int, encryptionOffset: Int, syntaxOffset: Int, revisionOffset: Int, entrypointOffset: Int, libraryOffset: Int) : Int {
            builder.startTable(6)
            addLibrary(builder, libraryOffset)
            addEntrypoint(builder, entrypointOffset)
            addRevision(builder, revisionOffset)
            addSyntax(builder, syntaxOffset)
            addEncryption(builder, encryptionOffset)
            addCodeFile(builder, codeFileOffset)
            return endProgCode(builder)
        }
        fun startProgCode(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addCodeFile(builder: FlatBufferBuilder, codeFile: Int) = builder.addOffset(0, codeFile, 0)
        fun addEncryption(builder: FlatBufferBuilder, encryption: Int) = builder.addOffset(1, encryption, 0)
        fun addSyntax(builder: FlatBufferBuilder, syntax: Int) = builder.addOffset(2, syntax, 0)
        fun addRevision(builder: FlatBufferBuilder, revision: Int) = builder.addOffset(3, revision, 0)
        fun addEntrypoint(builder: FlatBufferBuilder, entrypoint: Int) = builder.addOffset(4, entrypoint, 0)
        fun addLibrary(builder: FlatBufferBuilder, library: Int) = builder.addOffset(5, library, 0)
        fun createLibraryVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startLibraryVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endProgCode(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
