// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ProtStack : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ProtStack {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val pduProtocolType : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val pduProtocolTypeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun pduProtocolTypeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val physicalLinkType : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val physicalLinkTypeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun physicalLinkTypeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    fun comparamSubsetRefs(j: Int) : dataformat.ComParamSubSet? = comparamSubsetRefs(dataformat.ComParamSubSet(), j)
    fun comparamSubsetRefs(obj: dataformat.ComParamSubSet, j: Int) : dataformat.ComParamSubSet? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val comparamSubsetRefsLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsProtStack(_bb: ByteBuffer): ProtStack = getRootAsProtStack(_bb, ProtStack())
        fun getRootAsProtStack(_bb: ByteBuffer, obj: ProtStack): ProtStack {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createProtStack(builder: FlatBufferBuilder, shortNameOffset: Int, longNameOffset: Int, pduProtocolTypeOffset: Int, physicalLinkTypeOffset: Int, comparamSubsetRefsOffset: Int) : Int {
            builder.startTable(5)
            addComparamSubsetRefs(builder, comparamSubsetRefsOffset)
            addPhysicalLinkType(builder, physicalLinkTypeOffset)
            addPduProtocolType(builder, pduProtocolTypeOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            return endProtStack(builder)
        }
        fun startProtStack(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(1, longName, 0)
        fun addPduProtocolType(builder: FlatBufferBuilder, pduProtocolType: Int) = builder.addOffset(2, pduProtocolType, 0)
        fun addPhysicalLinkType(builder: FlatBufferBuilder, physicalLinkType: Int) = builder.addOffset(3, physicalLinkType, 0)
        fun addComparamSubsetRefs(builder: FlatBufferBuilder, comparamSubsetRefs: Int) = builder.addOffset(4, comparamSubsetRefs, 0)
        fun createComparamSubsetRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startComparamSubsetRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endProtStack(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
