// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class Radix private constructor() {
    companion object {
        const val HEX: Byte = 0
        const val DEC: Byte = 1
        const val BIN: Byte = 2
        const val OCT: Byte = 3
    }
}
