// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Reserved : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Reserved {
        __init(_i, _bb)
        return this
    }
    val bitLength : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsReserved(_bb: ByteBuffer): Reserved = getRootAsReserved(_bb, Reserved())
        fun getRootAsReserved(_bb: ByteBuffer, obj: Reserved): Reserved {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createReserved(builder: FlatBufferBuilder, bitLength: UInt) : Int {
            builder.startTable(1)
            addBitLength(builder, bitLength)
            return endReserved(builder)
        }
        fun startReserved(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addBitLength(builder: FlatBufferBuilder, bitLength: UInt) = builder.addInt(0, bitLength.toInt(), 0)
        fun endReserved(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
