// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class ResponseType private constructor() {
    companion object {
        const val POS_RESPONSE: Byte = 0
        const val NEG_RESPONSE: Byte = 1
        const val GLOBAL_NEG_RESPONSE: Byte = 2
    }
}
