// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Response : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Response {
        __init(_i, _bb)
        return this
    }
    val responseType : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    fun params(j: Int) : dataformat.Param? = params(dataformat.Param(), j)
    fun params(obj: dataformat.Param, j: Int) : dataformat.Param? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val paramsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val sdgs : dataformat.SDGS? get() = sdgs(dataformat.SDGS())
    fun sdgs(obj: dataformat.SDGS) : dataformat.SDGS? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsResponse(_bb: ByteBuffer): Response = getRootAsResponse(_bb, Response())
        fun getRootAsResponse(_bb: ByteBuffer, obj: Response): Response {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createResponse(builder: FlatBufferBuilder, responseType: Byte, paramsOffset: Int, sdgsOffset: Int) : Int {
            builder.startTable(3)
            addSdgs(builder, sdgsOffset)
            addParams(builder, paramsOffset)
            addResponseType(builder, responseType)
            return endResponse(builder)
        }
        fun startResponse(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addResponseType(builder: FlatBufferBuilder, responseType: Byte) = builder.addByte(0, responseType, 0)
        fun addParams(builder: FlatBufferBuilder, params: Int) = builder.addOffset(1, params, 0)
        fun createParamsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startParamsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(2, sdgs, 0)
        fun endResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
