// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ScaleConstr : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ScaleConstr {
        __init(_i, _bb)
        return this
    }
    val shortLabel : dataformat.Text? get() = shortLabel(dataformat.Text())
    fun shortLabel(obj: dataformat.Text) : dataformat.Text? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val lowerLimit : dataformat.Limit? get() = lowerLimit(dataformat.Limit())
    fun lowerLimit(obj: dataformat.Limit) : dataformat.Limit? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val upperLimit : dataformat.Limit? get() = upperLimit(dataformat.Limit())
    fun upperLimit(obj: dataformat.Limit) : dataformat.Limit? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val validity : Byte
        get() {
            val o = __offset(10)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsScaleConstr(_bb: ByteBuffer): ScaleConstr = getRootAsScaleConstr(_bb, ScaleConstr())
        fun getRootAsScaleConstr(_bb: ByteBuffer, obj: ScaleConstr): ScaleConstr {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createScaleConstr(builder: FlatBufferBuilder, shortLabelOffset: Int, lowerLimitOffset: Int, upperLimitOffset: Int, validity: Byte) : Int {
            builder.startTable(4)
            addUpperLimit(builder, upperLimitOffset)
            addLowerLimit(builder, lowerLimitOffset)
            addShortLabel(builder, shortLabelOffset)
            addValidity(builder, validity)
            return endScaleConstr(builder)
        }
        fun startScaleConstr(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addShortLabel(builder: FlatBufferBuilder, shortLabel: Int) = builder.addOffset(0, shortLabel, 0)
        fun addLowerLimit(builder: FlatBufferBuilder, lowerLimit: Int) = builder.addOffset(1, lowerLimit, 0)
        fun addUpperLimit(builder: FlatBufferBuilder, upperLimit: Int) = builder.addOffset(2, upperLimit, 0)
        fun addValidity(builder: FlatBufferBuilder, validity: Byte) = builder.addByte(3, validity, 0)
        fun endScaleConstr(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
