// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SD : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SD {
        __init(_i, _bb)
        return this
    }
    val value : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val valueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun valueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val si : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val siAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun siInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val ti : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val tiAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun tiInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsSD(_bb: ByteBuffer): SD = getRootAsSD(_bb, SD())
        fun getRootAsSD(_bb: ByteBuffer, obj: SD): SD {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSD(builder: FlatBufferBuilder, valueOffset: Int, siOffset: Int, tiOffset: Int) : Int {
            builder.startTable(3)
            addTi(builder, tiOffset)
            addSi(builder, siOffset)
            addValue(builder, valueOffset)
            return endSD(builder)
        }
        fun startSD(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addValue(builder: FlatBufferBuilder, value: Int) = builder.addOffset(0, value, 0)
        fun addSi(builder: FlatBufferBuilder, si: Int) = builder.addOffset(1, si, 0)
        fun addTi(builder: FlatBufferBuilder, ti: Int) = builder.addOffset(2, ti, 0)
        fun endSD(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
