// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SDG : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SDG {
        __init(_i, _bb)
        return this
    }
    val captionSn : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val captionSnAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun captionSnInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    fun sds(j: Int) : dataformat.SDOrSDG? = sds(dataformat.SDOrSDG(), j)
    fun sds(obj: dataformat.SDOrSDG, j: Int) : dataformat.SDOrSDG? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val sdsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val si : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val siAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun siInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsSDG(_bb: ByteBuffer): SDG = getRootAsSDG(_bb, SDG())
        fun getRootAsSDG(_bb: ByteBuffer, obj: SDG): SDG {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSDG(builder: FlatBufferBuilder, captionSnOffset: Int, sdsOffset: Int, siOffset: Int) : Int {
            builder.startTable(3)
            addSi(builder, siOffset)
            addSds(builder, sdsOffset)
            addCaptionSn(builder, captionSnOffset)
            return endSDG(builder)
        }
        fun startSDG(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addCaptionSn(builder: FlatBufferBuilder, captionSn: Int) = builder.addOffset(0, captionSn, 0)
        fun addSds(builder: FlatBufferBuilder, sds: Int) = builder.addOffset(1, sds, 0)
        fun createSdsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startSdsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSi(builder: FlatBufferBuilder, si: Int) = builder.addOffset(2, si, 0)
        fun endSDG(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
