// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SDGS : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SDGS {
        __init(_i, _bb)
        return this
    }
    fun sdgs(j: Int) : dataformat.SDG? = sdgs(dataformat.SDG(), j)
    fun sdgs(obj: dataformat.SDG, j: Int) : dataformat.SDG? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val sdgsLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsSDGS(_bb: ByteBuffer): SDGS = getRootAsSDGS(_bb, SDGS())
        fun getRootAsSDGS(_bb: ByteBuffer, obj: SDGS): SDGS {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSDGS(builder: FlatBufferBuilder, sdgsOffset: Int) : Int {
            builder.startTable(1)
            addSdgs(builder, sdgsOffset)
            return endSDGS(builder)
        }
        fun startSDGS(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(0, sdgs, 0)
        fun createSdgsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startSdgsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endSDGS(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
