// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SDOrSDG : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SDOrSDG {
        __init(_i, _bb)
        return this
    }
    val sdOrSdgType : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun sdOrSdg(obj: Table) : Table? {
        val o = __offset(6); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsSDOrSDG(_bb: ByteBuffer): SDOrSDG = getRootAsSDOrSDG(_bb, SDOrSDG())
        fun getRootAsSDOrSDG(_bb: ByteBuffer, obj: SDOrSDG): SDOrSDG {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSDOrSDG(builder: FlatBufferBuilder, sdOrSdgType: UByte, sdOrSdgOffset: Int) : Int {
            builder.startTable(2)
            addSdOrSdg(builder, sdOrSdgOffset)
            addSdOrSdgType(builder, sdOrSdgType)
            return endSDOrSDG(builder)
        }
        fun startSDOrSDG(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addSdOrSdgType(builder: FlatBufferBuilder, sdOrSdgType: UByte) = builder.addByte(0, sdOrSdgType.toByte(), 0)
        fun addSdOrSdg(builder: FlatBufferBuilder, sdOrSdg: Int) = builder.addOffset(1, sdOrSdg, 0)
        fun endSDOrSDG(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
