// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class SDxorSDG private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val SD: UByte = 1u
        const val SDG: UByte = 2u
    }
}
