// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class SimpleOrComplexValueEntry private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val SimpleValue: UByte = 1u
        const val ComplexValue: UByte = 2u
    }
}
