// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SingleEcuJob : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SingleEcuJob {
        __init(_i, _bb)
        return this
    }
    val diagComm : dataformat.DiagComm? get() = diagComm(dataformat.DiagComm())
    fun diagComm(obj: dataformat.DiagComm) : dataformat.DiagComm? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun progCodes(j: Int) : dataformat.ProgCode? = progCodes(dataformat.ProgCode(), j)
    fun progCodes(obj: dataformat.ProgCode, j: Int) : dataformat.ProgCode? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val progCodesLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    fun inputParams(j: Int) : dataformat.JobParam? = inputParams(dataformat.JobParam(), j)
    fun inputParams(obj: dataformat.JobParam, j: Int) : dataformat.JobParam? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val inputParamsLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    fun outputParams(j: Int) : dataformat.JobParam? = outputParams(dataformat.JobParam(), j)
    fun outputParams(obj: dataformat.JobParam, j: Int) : dataformat.JobParam? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val outputParamsLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    fun negOutputParams(j: Int) : dataformat.JobParam? = negOutputParams(dataformat.JobParam(), j)
    fun negOutputParams(obj: dataformat.JobParam, j: Int) : dataformat.JobParam? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val negOutputParamsLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsSingleEcuJob(_bb: ByteBuffer): SingleEcuJob = getRootAsSingleEcuJob(_bb, SingleEcuJob())
        fun getRootAsSingleEcuJob(_bb: ByteBuffer, obj: SingleEcuJob): SingleEcuJob {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSingleEcuJob(builder: FlatBufferBuilder, diagCommOffset: Int, progCodesOffset: Int, inputParamsOffset: Int, outputParamsOffset: Int, negOutputParamsOffset: Int) : Int {
            builder.startTable(5)
            addNegOutputParams(builder, negOutputParamsOffset)
            addOutputParams(builder, outputParamsOffset)
            addInputParams(builder, inputParamsOffset)
            addProgCodes(builder, progCodesOffset)
            addDiagComm(builder, diagCommOffset)
            return endSingleEcuJob(builder)
        }
        fun startSingleEcuJob(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addDiagComm(builder: FlatBufferBuilder, diagComm: Int) = builder.addOffset(0, diagComm, 0)
        fun addProgCodes(builder: FlatBufferBuilder, progCodes: Int) = builder.addOffset(1, progCodes, 0)
        fun createProgCodesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startProgCodesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addInputParams(builder: FlatBufferBuilder, inputParams: Int) = builder.addOffset(2, inputParams, 0)
        fun createInputParamsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startInputParamsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addOutputParams(builder: FlatBufferBuilder, outputParams: Int) = builder.addOffset(3, outputParams, 0)
        fun createOutputParamsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startOutputParamsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addNegOutputParams(builder: FlatBufferBuilder, negOutputParams: Int) = builder.addOffset(4, negOutputParams, 0)
        fun createNegOutputParamsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startNegOutputParamsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endSingleEcuJob(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
