// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class SpecificDOPData private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val NormalDOP: UByte = 1u
        const val EndOfPduField: UByte = 2u
        const val StaticField: UByte = 3u
        const val EnvDataDesc: UByte = 4u
        const val EnvData: UByte = 5u
        const val DTCDOP: UByte = 6u
        const val Structure: UByte = 7u
        const val MUXDOP: UByte = 8u
        const val DynamicLengthField: UByte = 9u
    }
}
