// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class SpecificDataType private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val LeadingLengthInfoType: UByte = 1u
        const val MinMaxLengthType: UByte = 2u
        const val ParamLengthInfoType: UByte = 3u
        const val StandardLengthType: UByte = 4u
    }
}
