// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class StandardLengthType : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StandardLengthType {
        __init(_i, _bb)
        return this
    }
    val bitLength : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    fun bitMask(j: Int) : UByte {
        val o = __offset(6)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val bitMaskLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val bitMaskAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun bitMaskInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val condensed : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsStandardLengthType(_bb: ByteBuffer): StandardLengthType = getRootAsStandardLengthType(_bb, StandardLengthType())
        fun getRootAsStandardLengthType(_bb: ByteBuffer, obj: StandardLengthType): StandardLengthType {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStandardLengthType(builder: FlatBufferBuilder, bitLength: UInt, bitMaskOffset: Int, condensed: Boolean) : Int {
            builder.startTable(3)
            addBitMask(builder, bitMaskOffset)
            addBitLength(builder, bitLength)
            addCondensed(builder, condensed)
            return endStandardLengthType(builder)
        }
        fun startStandardLengthType(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addBitLength(builder: FlatBufferBuilder, bitLength: UInt) = builder.addInt(0, bitLength.toInt(), 0)
        fun addBitMask(builder: FlatBufferBuilder, bitMask: Int) = builder.addOffset(1, bitMask, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createBitMaskVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        fun startBitMaskVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun addCondensed(builder: FlatBufferBuilder, condensed: Boolean) = builder.addBoolean(2, condensed, false)
        fun endStandardLengthType(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
