// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class StaticField : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StaticField {
        __init(_i, _bb)
        return this
    }
    val fixedNumberOfItems : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val itemByteSize : UInt
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val field : dataformat.Field? get() = field(dataformat.Field())
    fun field(obj: dataformat.Field) : dataformat.Field? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsStaticField(_bb: ByteBuffer): StaticField = getRootAsStaticField(_bb, StaticField())
        fun getRootAsStaticField(_bb: ByteBuffer, obj: StaticField): StaticField {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStaticField(builder: FlatBufferBuilder, fixedNumberOfItems: UInt, itemByteSize: UInt, fieldOffset: Int) : Int {
            builder.startTable(3)
            addField(builder, fieldOffset)
            addItemByteSize(builder, itemByteSize)
            addFixedNumberOfItems(builder, fixedNumberOfItems)
            return endStaticField(builder)
        }
        fun startStaticField(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addFixedNumberOfItems(builder: FlatBufferBuilder, fixedNumberOfItems: UInt) = builder.addInt(0, fixedNumberOfItems.toInt(), 0)
        fun addItemByteSize(builder: FlatBufferBuilder, itemByteSize: UInt) = builder.addInt(1, itemByteSize.toInt(), 0)
        fun addField(builder: FlatBufferBuilder, field: Int) = builder.addOffset(2, field, 0)
        fun endStaticField(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
