// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class StateTransition : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StateTransition {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val sourceShortNameRef : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sourceShortNameRefAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun sourceShortNameRefInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val targetShortNameRef : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val targetShortNameRefAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun targetShortNameRefInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsStateTransition(_bb: ByteBuffer): StateTransition = getRootAsStateTransition(_bb, StateTransition())
        fun getRootAsStateTransition(_bb: ByteBuffer, obj: StateTransition): StateTransition {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStateTransition(builder: FlatBufferBuilder, shortNameOffset: Int, sourceShortNameRefOffset: Int, targetShortNameRefOffset: Int) : Int {
            builder.startTable(3)
            addTargetShortNameRef(builder, targetShortNameRefOffset)
            addSourceShortNameRef(builder, sourceShortNameRefOffset)
            addShortName(builder, shortNameOffset)
            return endStateTransition(builder)
        }
        fun startStateTransition(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addSourceShortNameRef(builder: FlatBufferBuilder, sourceShortNameRef: Int) = builder.addOffset(1, sourceShortNameRef, 0)
        fun addTargetShortNameRef(builder: FlatBufferBuilder, targetShortNameRef: Int) = builder.addOffset(2, targetShortNameRef, 0)
        fun endStateTransition(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
