// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class StateChart : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StateChart {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val semantic : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val semanticAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun semanticInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    fun stateTransitions(j: Int) : dataformat.StateTransition? = stateTransitions(dataformat.StateTransition(), j)
    fun stateTransitions(obj: dataformat.StateTransition, j: Int) : dataformat.StateTransition? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val stateTransitionsLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val startStateShortNameRef : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val startStateShortNameRefAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun startStateShortNameRefInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    fun states(j: Int) : dataformat.State? = states(dataformat.State(), j)
    fun states(obj: dataformat.State, j: Int) : dataformat.State? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val statesLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsStateChart(_bb: ByteBuffer): StateChart = getRootAsStateChart(_bb, StateChart())
        fun getRootAsStateChart(_bb: ByteBuffer, obj: StateChart): StateChart {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStateChart(builder: FlatBufferBuilder, shortNameOffset: Int, semanticOffset: Int, stateTransitionsOffset: Int, startStateShortNameRefOffset: Int, statesOffset: Int) : Int {
            builder.startTable(5)
            addStates(builder, statesOffset)
            addStartStateShortNameRef(builder, startStateShortNameRefOffset)
            addStateTransitions(builder, stateTransitionsOffset)
            addSemantic(builder, semanticOffset)
            addShortName(builder, shortNameOffset)
            return endStateChart(builder)
        }
        fun startStateChart(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addSemantic(builder: FlatBufferBuilder, semantic: Int) = builder.addOffset(1, semantic, 0)
        fun addStateTransitions(builder: FlatBufferBuilder, stateTransitions: Int) = builder.addOffset(2, stateTransitions, 0)
        fun createStateTransitionsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStateTransitionsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addStartStateShortNameRef(builder: FlatBufferBuilder, startStateShortNameRef: Int) = builder.addOffset(3, startStateShortNameRef, 0)
        fun addStates(builder: FlatBufferBuilder, states: Int) = builder.addOffset(4, states, 0)
        fun createStatesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStatesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endStateChart(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
