// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class StateTransitionRef : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StateTransitionRef {
        __init(_i, _bb)
        return this
    }
    val value : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val valueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun valueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val stateTransition : dataformat.StateTransition? get() = stateTransition(dataformat.StateTransition())
    fun stateTransition(obj: dataformat.StateTransition) : dataformat.StateTransition? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsStateTransitionRef(_bb: ByteBuffer): StateTransitionRef = getRootAsStateTransitionRef(_bb, StateTransitionRef())
        fun getRootAsStateTransitionRef(_bb: ByteBuffer, obj: StateTransitionRef): StateTransitionRef {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStateTransitionRef(builder: FlatBufferBuilder, valueOffset: Int, stateTransitionOffset: Int) : Int {
            builder.startTable(2)
            addStateTransition(builder, stateTransitionOffset)
            addValue(builder, valueOffset)
            return endStateTransitionRef(builder)
        }
        fun startStateTransitionRef(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addValue(builder: FlatBufferBuilder, value: Int) = builder.addOffset(0, value, 0)
        fun addStateTransition(builder: FlatBufferBuilder, stateTransition: Int) = builder.addOffset(1, stateTransition, 0)
        fun endStateTransitionRef(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
