// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TableRow : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TableRow {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val key : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val keyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun keyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val dop : dataformat.DOP? get() = dop(dataformat.DOP())
    fun dop(obj: dataformat.DOP) : dataformat.DOP? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val structure : dataformat.DOP? get() = structure(dataformat.DOP())
    fun structure(obj: dataformat.DOP) : dataformat.DOP? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val sdgs : dataformat.SDGS? get() = sdgs(dataformat.SDGS())
    fun sdgs(obj: dataformat.SDGS) : dataformat.SDGS? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val audience : dataformat.Audience? get() = audience(dataformat.Audience())
    fun audience(obj: dataformat.Audience) : dataformat.Audience? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun functClassRefs(j: Int) : dataformat.FunctClass? = functClassRefs(dataformat.FunctClass(), j)
    fun functClassRefs(obj: dataformat.FunctClass, j: Int) : dataformat.FunctClass? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val functClassRefsLength : Int
        get() {
            val o = __offset(18); return if (o != 0) __vector_len(o) else 0
        }
    fun stateTransitionRefs(j: Int) : dataformat.StateTransitionRef? = stateTransitionRefs(dataformat.StateTransitionRef(), j)
    fun stateTransitionRefs(obj: dataformat.StateTransitionRef, j: Int) : dataformat.StateTransitionRef? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val stateTransitionRefsLength : Int
        get() {
            val o = __offset(20); return if (o != 0) __vector_len(o) else 0
        }
    fun preConditionStateRefs(j: Int) : dataformat.PreConditionStateRef? = preConditionStateRefs(dataformat.PreConditionStateRef(), j)
    fun preConditionStateRefs(obj: dataformat.PreConditionStateRef, j: Int) : dataformat.PreConditionStateRef? {
        val o = __offset(22)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val preConditionStateRefsLength : Int
        get() {
            val o = __offset(22); return if (o != 0) __vector_len(o) else 0
        }
    val isExecutable : Boolean
        get() {
            val o = __offset(24)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else true
        }
    val semantic : String?
        get() {
            val o = __offset(26)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val semanticAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(26, 1)
    fun semanticInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 26, 1)
    val isMandatory : Boolean
        get() {
            val o = __offset(28)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isFinal : Boolean
        get() {
            val o = __offset(30)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsTableRow(_bb: ByteBuffer): TableRow = getRootAsTableRow(_bb, TableRow())
        fun getRootAsTableRow(_bb: ByteBuffer, obj: TableRow): TableRow {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTableRow(builder: FlatBufferBuilder, shortNameOffset: Int, longNameOffset: Int, keyOffset: Int, dopOffset: Int, structureOffset: Int, sdgsOffset: Int, audienceOffset: Int, functClassRefsOffset: Int, stateTransitionRefsOffset: Int, preConditionStateRefsOffset: Int, isExecutable: Boolean, semanticOffset: Int, isMandatory: Boolean, isFinal: Boolean) : Int {
            builder.startTable(14)
            addSemantic(builder, semanticOffset)
            addPreConditionStateRefs(builder, preConditionStateRefsOffset)
            addStateTransitionRefs(builder, stateTransitionRefsOffset)
            addFunctClassRefs(builder, functClassRefsOffset)
            addAudience(builder, audienceOffset)
            addSdgs(builder, sdgsOffset)
            addStructure(builder, structureOffset)
            addDop(builder, dopOffset)
            addKey(builder, keyOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            addIsFinal(builder, isFinal)
            addIsMandatory(builder, isMandatory)
            addIsExecutable(builder, isExecutable)
            return endTableRow(builder)
        }
        fun startTableRow(builder: FlatBufferBuilder) = builder.startTable(14)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(1, longName, 0)
        fun addKey(builder: FlatBufferBuilder, key: Int) = builder.addOffset(2, key, 0)
        fun addDop(builder: FlatBufferBuilder, dop: Int) = builder.addOffset(3, dop, 0)
        fun addStructure(builder: FlatBufferBuilder, structure: Int) = builder.addOffset(4, structure, 0)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(5, sdgs, 0)
        fun addAudience(builder: FlatBufferBuilder, audience: Int) = builder.addOffset(6, audience, 0)
        fun addFunctClassRefs(builder: FlatBufferBuilder, functClassRefs: Int) = builder.addOffset(7, functClassRefs, 0)
        fun createFunctClassRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startFunctClassRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addStateTransitionRefs(builder: FlatBufferBuilder, stateTransitionRefs: Int) = builder.addOffset(8, stateTransitionRefs, 0)
        fun createStateTransitionRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStateTransitionRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addPreConditionStateRefs(builder: FlatBufferBuilder, preConditionStateRefs: Int) = builder.addOffset(9, preConditionStateRefs, 0)
        fun createPreConditionStateRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startPreConditionStateRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addIsExecutable(builder: FlatBufferBuilder, isExecutable: Boolean) = builder.addBoolean(10, isExecutable, true)
        fun addSemantic(builder: FlatBufferBuilder, semantic: Int) = builder.addOffset(11, semantic, 0)
        fun addIsMandatory(builder: FlatBufferBuilder, isMandatory: Boolean) = builder.addBoolean(12, isMandatory, false)
        fun addIsFinal(builder: FlatBufferBuilder, isFinal: Boolean) = builder.addBoolean(13, isFinal, false)
        fun endTableRow(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
