// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TableKey : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TableKey {
        __init(_i, _bb)
        return this
    }
    val tableKeyReferenceType : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun tableKeyReference(obj: Table) : Table? {
        val o = __offset(6); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsTableKey(_bb: ByteBuffer): TableKey = getRootAsTableKey(_bb, TableKey())
        fun getRootAsTableKey(_bb: ByteBuffer, obj: TableKey): TableKey {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTableKey(builder: FlatBufferBuilder, tableKeyReferenceType: UByte, tableKeyReferenceOffset: Int) : Int {
            builder.startTable(2)
            addTableKeyReference(builder, tableKeyReferenceOffset)
            addTableKeyReferenceType(builder, tableKeyReferenceType)
            return endTableKey(builder)
        }
        fun startTableKey(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addTableKeyReferenceType(builder: FlatBufferBuilder, tableKeyReferenceType: UByte) = builder.addByte(0, tableKeyReferenceType.toByte(), 0)
        fun addTableKeyReference(builder: FlatBufferBuilder, tableKeyReference: Int) = builder.addOffset(1, tableKeyReference, 0)
        fun endTableKey(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
