// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TableDop : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TableDop {
        __init(_i, _bb)
        return this
    }
    val semantic : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val semanticAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun semanticInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val shortName : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val keyLabel : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val keyLabelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun keyLabelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val structLabel : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val structLabelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun structLabelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val keyDop : dataformat.DOP? get() = keyDop(dataformat.DOP())
    fun keyDop(obj: dataformat.DOP) : dataformat.DOP? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun rows(j: Int) : dataformat.TableRow? = rows(dataformat.TableRow(), j)
    fun rows(obj: dataformat.TableRow, j: Int) : dataformat.TableRow? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val rowsLength : Int
        get() {
            val o = __offset(16); return if (o != 0) __vector_len(o) else 0
        }
    fun diagCommConnector(j: Int) : dataformat.TableDiagCommConnector? = diagCommConnector(dataformat.TableDiagCommConnector(), j)
    fun diagCommConnector(obj: dataformat.TableDiagCommConnector, j: Int) : dataformat.TableDiagCommConnector? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val diagCommConnectorLength : Int
        get() {
            val o = __offset(18); return if (o != 0) __vector_len(o) else 0
        }
    val sdgs : dataformat.SDGS? get() = sdgs(dataformat.SDGS())
    fun sdgs(obj: dataformat.SDGS) : dataformat.SDGS? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsTableDop(_bb: ByteBuffer): TableDop = getRootAsTableDop(_bb, TableDop())
        fun getRootAsTableDop(_bb: ByteBuffer, obj: TableDop): TableDop {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTableDop(builder: FlatBufferBuilder, semanticOffset: Int, shortNameOffset: Int, longNameOffset: Int, keyLabelOffset: Int, structLabelOffset: Int, keyDopOffset: Int, rowsOffset: Int, diagCommConnectorOffset: Int, sdgsOffset: Int) : Int {
            builder.startTable(9)
            addSdgs(builder, sdgsOffset)
            addDiagCommConnector(builder, diagCommConnectorOffset)
            addRows(builder, rowsOffset)
            addKeyDop(builder, keyDopOffset)
            addStructLabel(builder, structLabelOffset)
            addKeyLabel(builder, keyLabelOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            addSemantic(builder, semanticOffset)
            return endTableDop(builder)
        }
        fun startTableDop(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addSemantic(builder: FlatBufferBuilder, semantic: Int) = builder.addOffset(0, semantic, 0)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(1, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(2, longName, 0)
        fun addKeyLabel(builder: FlatBufferBuilder, keyLabel: Int) = builder.addOffset(3, keyLabel, 0)
        fun addStructLabel(builder: FlatBufferBuilder, structLabel: Int) = builder.addOffset(4, structLabel, 0)
        fun addKeyDop(builder: FlatBufferBuilder, keyDop: Int) = builder.addOffset(5, keyDop, 0)
        fun addRows(builder: FlatBufferBuilder, rows: Int) = builder.addOffset(6, rows, 0)
        fun createRowsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startRowsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDiagCommConnector(builder: FlatBufferBuilder, diagCommConnector: Int) = builder.addOffset(7, diagCommConnector, 0)
        fun createDiagCommConnectorVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDiagCommConnectorVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(8, sdgs, 0)
        fun endTableDop(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
