// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TableDiagCommConnector : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TableDiagCommConnector {
        __init(_i, _bb)
        return this
    }
    val diagCommType : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun diagComm(obj: Table) : Table? {
        val o = __offset(6); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    val semantic : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val semanticAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun semanticInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsTableDiagCommConnector(_bb: ByteBuffer): TableDiagCommConnector = getRootAsTableDiagCommConnector(_bb, TableDiagCommConnector())
        fun getRootAsTableDiagCommConnector(_bb: ByteBuffer, obj: TableDiagCommConnector): TableDiagCommConnector {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTableDiagCommConnector(builder: FlatBufferBuilder, diagCommType: UByte, diagCommOffset: Int, semanticOffset: Int) : Int {
            builder.startTable(3)
            addSemantic(builder, semanticOffset)
            addDiagComm(builder, diagCommOffset)
            addDiagCommType(builder, diagCommType)
            return endTableDiagCommConnector(builder)
        }
        fun startTableDiagCommConnector(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addDiagCommType(builder: FlatBufferBuilder, diagCommType: UByte) = builder.addByte(0, diagCommType.toByte(), 0)
        fun addDiagComm(builder: FlatBufferBuilder, diagComm: Int) = builder.addOffset(1, diagComm, 0)
        fun addSemantic(builder: FlatBufferBuilder, semantic: Int) = builder.addOffset(2, semantic, 0)
        fun endTableDiagCommConnector(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
