// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class TableEntryRowFragment private constructor() {
    companion object {
        const val KEY: Byte = 0
        const val STRUCT: Byte = 1
    }
}
