// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TableEntry : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TableEntry {
        __init(_i, _bb)
        return this
    }
    val param : dataformat.Param? get() = param(dataformat.Param())
    fun param(obj: dataformat.Param) : dataformat.Param? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val target : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val tableRow : dataformat.TableRow? get() = tableRow(dataformat.TableRow())
    fun tableRow(obj: dataformat.TableRow) : dataformat.TableRow? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsTableEntry(_bb: ByteBuffer): TableEntry = getRootAsTableEntry(_bb, TableEntry())
        fun getRootAsTableEntry(_bb: ByteBuffer, obj: TableEntry): TableEntry {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTableEntry(builder: FlatBufferBuilder, paramOffset: Int, target: Byte, tableRowOffset: Int) : Int {
            builder.startTable(3)
            addTableRow(builder, tableRowOffset)
            addParam(builder, paramOffset)
            addTarget(builder, target)
            return endTableEntry(builder)
        }
        fun startTableEntry(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addParam(builder: FlatBufferBuilder, param: Int) = builder.addOffset(0, param, 0)
        fun addTarget(builder: FlatBufferBuilder, target: Byte) = builder.addByte(1, target, 0)
        fun addTableRow(builder: FlatBufferBuilder, tableRow: Int) = builder.addOffset(2, tableRow, 0)
        fun endTableEntry(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
