// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class TableKeyReference private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val TableDop: UByte = 1u
        const val TableRow: UByte = 2u
    }
}
