// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TableStruct : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TableStruct {
        __init(_i, _bb)
        return this
    }
    val tableKey : dataformat.Param? get() = tableKey(dataformat.Param())
    fun tableKey(obj: dataformat.Param) : dataformat.Param? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsTableStruct(_bb: ByteBuffer): TableStruct = getRootAsTableStruct(_bb, TableStruct())
        fun getRootAsTableStruct(_bb: ByteBuffer, obj: TableStruct): TableStruct {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTableStruct(builder: FlatBufferBuilder, tableKeyOffset: Int) : Int {
            builder.startTable(1)
            addTableKey(builder, tableKeyOffset)
            return endTableStruct(builder)
        }
        fun startTableStruct(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addTableKey(builder: FlatBufferBuilder, tableKey: Int) = builder.addOffset(0, tableKey, 0)
        fun endTableStruct(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
