// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class Termination private constructor() {
    companion object {
        const val END_OF_PDU: Byte = 0
        const val ZERO: Byte = 1
        const val HEX_FF: Byte = 2
    }
}
