// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class TransmissionMode private constructor() {
    companion object {
        const val SEND_ONLY: Byte = 0
        const val RECEIVE_ONLY: Byte = 1
        const val SEND_AND_RECEIVE: Byte = 2
        const val SEND_OR_RECEIVE: Byte = 3
    }
}
