// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class UnitGroup : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : UnitGroup {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val longName : dataformat.LongName? get() = longName(dataformat.LongName())
    fun longName(obj: dataformat.LongName) : dataformat.LongName? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun unitrefs(j: Int) : dataformat.Unit? = unitrefs(dataformat.Unit(), j)
    fun unitrefs(obj: dataformat.Unit, j: Int) : dataformat.Unit? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val unitrefsLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsUnitGroup(_bb: ByteBuffer): UnitGroup = getRootAsUnitGroup(_bb, UnitGroup())
        fun getRootAsUnitGroup(_bb: ByteBuffer, obj: UnitGroup): UnitGroup {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createUnitGroup(builder: FlatBufferBuilder, shortNameOffset: Int, longNameOffset: Int, unitrefsOffset: Int) : Int {
            builder.startTable(3)
            addUnitrefs(builder, unitrefsOffset)
            addLongName(builder, longNameOffset)
            addShortName(builder, shortNameOffset)
            return endUnitGroup(builder)
        }
        fun startUnitGroup(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addLongName(builder: FlatBufferBuilder, longName: Int) = builder.addOffset(1, longName, 0)
        fun addUnitrefs(builder: FlatBufferBuilder, unitrefs: Int) = builder.addOffset(2, unitrefs, 0)
        fun createUnitrefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startUnitrefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endUnitGroup(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
