// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class UnitGroupCategory private constructor() {
    companion object {
        const val COUNTRY: Byte = 0
        const val EQUIV_UNITS: Byte = 1
    }
}
