// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Unit : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Unit {
        __init(_i, _bb)
        return this
    }
    val shortName : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun shortNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val displayName : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val displayNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun displayNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val factorsitounit : Double?
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getDouble(o + bb_pos) else null
        }
    val offsetitounit : Double?
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getDouble(o + bb_pos) else null
        }
    val physicalDimension : dataformat.PhysicalDimension? get() = physicalDimension(dataformat.PhysicalDimension())
    fun physicalDimension(obj: dataformat.PhysicalDimension) : dataformat.PhysicalDimension? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsUnit(_bb: ByteBuffer): Unit = getRootAsUnit(_bb, Unit())
        fun getRootAsUnit(_bb: ByteBuffer, obj: Unit): Unit {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createUnit(builder: FlatBufferBuilder, shortNameOffset: Int, displayNameOffset: Int, factorsitounit: Double?, offsetitounit: Double?, physicalDimensionOffset: Int) : Int {
            builder.startTable(5)
            offsetitounit?.run { addOffsetitounit(builder, offsetitounit) }
            factorsitounit?.run { addFactorsitounit(builder, factorsitounit) }
            addPhysicalDimension(builder, physicalDimensionOffset)
            addDisplayName(builder, displayNameOffset)
            addShortName(builder, shortNameOffset)
            return endUnit(builder)
        }
        fun startUnit(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addShortName(builder: FlatBufferBuilder, shortName: Int) = builder.addOffset(0, shortName, 0)
        fun addDisplayName(builder: FlatBufferBuilder, displayName: Int) = builder.addOffset(1, displayName, 0)
        fun addFactorsitounit(builder: FlatBufferBuilder, factorsitounit: Double) = builder.addDouble(2, factorsitounit, 0.0)
        fun addOffsetitounit(builder: FlatBufferBuilder, offsetitounit: Double) = builder.addDouble(3, offsetitounit, 0.0)
        fun addPhysicalDimension(builder: FlatBufferBuilder, physicalDimension: Int) = builder.addOffset(4, physicalDimension, 0)
        fun endUnit(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
