// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class UnitSpec : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : UnitSpec {
        __init(_i, _bb)
        return this
    }
    fun unitGroups(j: Int) : dataformat.UnitGroup? = unitGroups(dataformat.UnitGroup(), j)
    fun unitGroups(obj: dataformat.UnitGroup, j: Int) : dataformat.UnitGroup? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val unitGroupsLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    fun units(j: Int) : dataformat.Unit? = units(dataformat.Unit(), j)
    fun units(obj: dataformat.Unit, j: Int) : dataformat.Unit? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val unitsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    fun physicalDimensions(j: Int) : dataformat.PhysicalDimension? = physicalDimensions(dataformat.PhysicalDimension(), j)
    fun physicalDimensions(obj: dataformat.PhysicalDimension, j: Int) : dataformat.PhysicalDimension? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val physicalDimensionsLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val sdgs : dataformat.SDGS? get() = sdgs(dataformat.SDGS())
    fun sdgs(obj: dataformat.SDGS) : dataformat.SDGS? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsUnitSpec(_bb: ByteBuffer): UnitSpec = getRootAsUnitSpec(_bb, UnitSpec())
        fun getRootAsUnitSpec(_bb: ByteBuffer, obj: UnitSpec): UnitSpec {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createUnitSpec(builder: FlatBufferBuilder, unitGroupsOffset: Int, unitsOffset: Int, physicalDimensionsOffset: Int, sdgsOffset: Int) : Int {
            builder.startTable(4)
            addSdgs(builder, sdgsOffset)
            addPhysicalDimensions(builder, physicalDimensionsOffset)
            addUnits(builder, unitsOffset)
            addUnitGroups(builder, unitGroupsOffset)
            return endUnitSpec(builder)
        }
        fun startUnitSpec(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addUnitGroups(builder: FlatBufferBuilder, unitGroups: Int) = builder.addOffset(0, unitGroups, 0)
        fun createUnitGroupsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startUnitGroupsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addUnits(builder: FlatBufferBuilder, units: Int) = builder.addOffset(1, units, 0)
        fun createUnitsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startUnitsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addPhysicalDimensions(builder: FlatBufferBuilder, physicalDimensions: Int) = builder.addOffset(2, physicalDimensions, 0)
        fun createPhysicalDimensionsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startPhysicalDimensionsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSdgs(builder: FlatBufferBuilder, sdgs: Int) = builder.addOffset(3, sdgs, 0)
        fun endUnitSpec(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
