// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

@Suppress("unused")
class ValidType private constructor() {
    companion object {
        const val VALID: Byte = 0
        const val NOT_VALID: Byte = 1
        const val NOT_DEFINED: Byte = 2
        const val NOT_AVAILABLE: Byte = 3
    }
}
