// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Value : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Value {
        __init(_i, _bb)
        return this
    }
    val physicalDefaultValue : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val physicalDefaultValueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun physicalDefaultValueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val dop : dataformat.DOP? get() = dop(dataformat.DOP())
    fun dop(obj: dataformat.DOP) : dataformat.DOP? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsValue(_bb: ByteBuffer): Value = getRootAsValue(_bb, Value())
        fun getRootAsValue(_bb: ByteBuffer, obj: Value): Value {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createValue(builder: FlatBufferBuilder, physicalDefaultValueOffset: Int, dopOffset: Int) : Int {
            builder.startTable(2)
            addDop(builder, dopOffset)
            addPhysicalDefaultValue(builder, physicalDefaultValueOffset)
            return endValue(builder)
        }
        fun startValue(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addPhysicalDefaultValue(builder: FlatBufferBuilder, physicalDefaultValue: Int) = builder.addOffset(0, physicalDefaultValue, 0)
        fun addDop(builder: FlatBufferBuilder, dop: Int) = builder.addOffset(1, dop, 0)
        fun endValue(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
