// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Variant : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Variant {
        __init(_i, _bb)
        return this
    }
    val diagLayer : dataformat.DiagLayer? get() = diagLayer(dataformat.DiagLayer())
    fun diagLayer(obj: dataformat.DiagLayer) : dataformat.DiagLayer? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val isBaseVariant : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    fun variantPattern(j: Int) : dataformat.VariantPattern? = variantPattern(dataformat.VariantPattern(), j)
    fun variantPattern(obj: dataformat.VariantPattern, j: Int) : dataformat.VariantPattern? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val variantPatternLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    fun parentRefs(j: Int) : dataformat.ParentRef? = parentRefs(dataformat.ParentRef(), j)
    fun parentRefs(obj: dataformat.ParentRef, j: Int) : dataformat.ParentRef? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val parentRefsLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsVariant(_bb: ByteBuffer): Variant = getRootAsVariant(_bb, Variant())
        fun getRootAsVariant(_bb: ByteBuffer, obj: Variant): Variant {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createVariant(builder: FlatBufferBuilder, diagLayerOffset: Int, isBaseVariant: Boolean, variantPatternOffset: Int, parentRefsOffset: Int) : Int {
            builder.startTable(4)
            addParentRefs(builder, parentRefsOffset)
            addVariantPattern(builder, variantPatternOffset)
            addDiagLayer(builder, diagLayerOffset)
            addIsBaseVariant(builder, isBaseVariant)
            return endVariant(builder)
        }
        fun startVariant(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addDiagLayer(builder: FlatBufferBuilder, diagLayer: Int) = builder.addOffset(0, diagLayer, 0)
        fun addIsBaseVariant(builder: FlatBufferBuilder, isBaseVariant: Boolean) = builder.addBoolean(1, isBaseVariant, false)
        fun addVariantPattern(builder: FlatBufferBuilder, variantPattern: Int) = builder.addOffset(2, variantPattern, 0)
        fun createVariantPatternVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startVariantPatternVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addParentRefs(builder: FlatBufferBuilder, parentRefs: Int) = builder.addOffset(3, parentRefs, 0)
        fun createParentRefsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startParentRefsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endVariant(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
