// automatically generated by the FlatBuffers compiler, do not modify

package dataformat

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class VariantPattern : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : VariantPattern {
        __init(_i, _bb)
        return this
    }
    fun matchingParameter(j: Int) : dataformat.MatchingParameter? = matchingParameter(dataformat.MatchingParameter(), j)
    fun matchingParameter(obj: dataformat.MatchingParameter, j: Int) : dataformat.MatchingParameter? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val matchingParameterLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsVariantPattern(_bb: ByteBuffer): VariantPattern = getRootAsVariantPattern(_bb, VariantPattern())
        fun getRootAsVariantPattern(_bb: ByteBuffer, obj: VariantPattern): VariantPattern {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createVariantPattern(builder: FlatBufferBuilder, matchingParameterOffset: Int) : Int {
            builder.startTable(1)
            addMatchingParameter(builder, matchingParameterOffset)
            return endVariantPattern(builder)
        }
        fun startVariantPattern(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addMatchingParameter(builder: FlatBufferBuilder, matchingParameter: Int) = builder.addOffset(0, matchingParameter, 0)
        fun createMatchingParameterVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startMatchingParameterVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endVariantPattern(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
