# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: \.(patch|diff|lock|json)$
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
        args: ["-formatter", "type=basic,retain_line_breaks_single=true"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff-check
        args: [--output-format=full]
      - id: ruff-format
        args: [--diff]
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse
  - repo: local
    hooks:
      - id: reuse-annotate
        name: Add missing license headers (REUSE)
        entry: uv run reuse-annotate-hook.py
        language: system
        pass_filenames: true
        exclude: ^(LICENSE|NOTICE|CONTRIBUTORS)$
      - id: cargo-fmt-long-lines
        name: Rust Format - Fix long lines and unformatted code
        entry: bash -c '[ -f Cargo.toml ] && cargo fmt --check -- --config error_on_unformatted=true,error_on_line_overflow=true,format_strings=true || exit 0'
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-fmt-import-order
        name: Rust Format - Fix import order
        entry: bash -c '[ -f Cargo.toml ] && cargo fmt --check -- --config group_imports=StdExternalCrate || exit 0'
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-fmt-imports-granularity
        name: Rust Format - Fix imports granularity
        entry: bash -c '[ -f Cargo.toml ] && cargo fmt --check -- --config imports_granularity=Crate || exit 0'
        language: system
        types: [rust]
        pass_filenames: false
      - id: validate-cargo-lints
        name: Validate Cargo Lints
        entry: uv run shared-lints/check_cargo_lints.py Cargo.toml
        language: system
        types: [rust]
        pass_filenames: false
